/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Software_Jframes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asbar Ali
 */
public class Other_expenses extends javax.swing.JInternalFrame {

    /**
     * Creates new form Other_expenses
     */
    public Other_expenses() {
        initComponents();

        setdate();
        settime();
        auto_inc();
        loadtable();
        
        jRadioButton1.setSelected(true);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        
        jTextField5.setEnabled(false);
        jLabel6.setEnabled(false);
      
        chart chart = new chart();
        chart.barchart(jDesktopPane1);
        
    }
    void settime(){
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                jTextField3.setText(sdf.format(d));
            }
        }).start();
    }
    void setdate(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String da= sdf.format(d);
        jTextField2.setText(da);
    }
   
     void auto_inc() {
         
       
        try {
            ResultSet rs= db.statement().executeQuery("select max(exp_id) from other_exp");
//            String ids= jTextField1.getText();
//            
//             if(ids.equals("")|| ids.equals(null) ){
//                    jTextField1.setText(1+"");}
          
           while(rs.next()){
                  
               int id = rs.getInt(1);
                
                
                if(id == 0 ){
                    jTextField1.setText(1+"");
                }
                
                System.out.println(id);
               
                
                    jTextField1.setText((id+1)+"");
                
            }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 200, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, 30));

        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));

        jLabel3.setText("Time");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));

        jLabel4.setText("Expence Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, -1));

        jLabel5.setText("Payment Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Cash");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cheque");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel6.setText("Cheque Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 20));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 200, -1));

        jLabel7.setText("Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 120, 30));

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 120, 30));

        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date", "Time", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 1190, 160));

        jLabel8.setText("Daily Expeses On");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Last Week", "Last Month" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 140, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Add Expense");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 620, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 180));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText("Overview Of Expenses");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1190, 30));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("View Expenses");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 500, 30));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 550, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jLabel6.setEnabled(false);
        jTextField5.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jTextField5.setEnabled(true);
        jLabel6.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
       
        
       String id= jTextField1.getText();
       String date= jTextField2.getText();
       String time= jTextField3.getText();
       String exp= jTextField6.getText();
       String amount = jTextField4.getText();
       String cheq=null;
       int i=0;
        try {
           ResultSet rs= db.statement().executeQuery("select exp_id from other_exp");
            while(rs.next()){
                if(rs.getString("exp_id").equals(id)){
                    i=1;
                }
            }
            if(i==1){
                JOptionPane.showMessageDialog(null,"Please enter for new id","Error Message",JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
       if(id.equals("") || id.equals(null)){
           JOptionPane.showMessageDialog(null,"Please enter the supply id","Error Message",JOptionPane.ERROR_MESSAGE);
           return;
       }else if( exp.equals("") || exp.equals(null) ){
           JOptionPane.showMessageDialog(null,"Please enter the Expense name","Error Message",JOptionPane.ERROR_MESSAGE);
           return;
       }else if(amount.equals("") || amount.equals(null)){
           JOptionPane.showMessageDialog(null,"Please enter the Amount","Error Message",JOptionPane.ERROR_MESSAGE);
           return;
       }else if (!amount.matches("[0-9]+")) {
     JOptionPane.showMessageDialog(null,"Please enter the numbers","Error",JOptionPane.ERROR_MESSAGE);
            return;
}
       int cheq1=0;
        dtm.setRowCount(0);
       
       if(jRadioButton1.isSelected()){
           
       }else{
           cheq= jTextField5.getText();
          
           if(cheq.equals("") || cheq.equals(null)){
               JOptionPane.showMessageDialog(null,"Please enter the cheque number","Error Message",JOptionPane.ERROR_MESSAGE);
               return;
           }else if(cheq.length()>15){
               JOptionPane.showMessageDialog(null,"Please enter the valid cheque number","Error Message",JOptionPane.ERROR_MESSAGE);
               return;
         
           }
            cheq1= Integer.parseInt(cheq);
            
       }
      
      
        try {
         db.statement().executeUpdate("insert into other_exp (exp_id, name, date, time, Amount,cheq_no)"
                   + " values ('"+id+"','"+exp+"','"+date+"','"+time+"','"+amount+"',"+cheq1+")");
           
            JOptionPane.showMessageDialog(null,"Successfully Saved","Success Message",JOptionPane.INFORMATION_MESSAGE);
            jTextField6.setText("");
            jTextField5.setText("");
            jTextField4.setText("");
            
            loadtable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int j= jTable1.getSelectedRow();
        
       String i=  jTable1.getValueAt(j, 0).toString();
       jTextField1.setText(i);
       jTextField6.setText(jTable1.getValueAt(j, 1).toString());
       jTextField4.setText(jTable1.getValueAt(j,4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        
        String id= jTextField1.getText();
        
        String date= jTextField2.getText();
        String time= jTextField3.getText();
        String exp= jTextField6.getText();
        String cheq= jTextField5.getText();  
        
        Integer int_id = Integer.parseInt(id);
       
        if(exp.equals("") || exp.equals(null)){
                 JOptionPane.showMessageDialog(null,"Please enter the Expense Name","Error Message", JOptionPane.ERROR_MESSAGE);
                 return;
            
        }
        
        
        if(jRadioButton2.isSelected()){
              if(cheq.equals("") || cheq.equals(null)){
                 JOptionPane.showMessageDialog(null,"Please enter the cheq field","Error Message", JOptionPane.ERROR_MESSAGE);
                 return;
             }
        }else{
           
        }
        
        String amount = jTextField4.getText();
       
        
         try {
           int i=0;
           ResultSet rs= db.statement().executeQuery("select exp_id from  other_exp");
           
           while(rs.next()){
               if(id.equals(rs.getString("exp_id"))){
                   i=i+1;
                   System.out.println(rs.getInt("exp_id"));
               }
           }
           if(i==0){
                JOptionPane.showMessageDialog(null,"No existing supply id for this number","Error Message",JOptionPane.ERROR_MESSAGE);
                return;
           }else if(amount.equals("") || amount.equals(null)){
           JOptionPane.showMessageDialog(null,"Please enter the Amount","Error Message",JOptionPane.ERROR_MESSAGE);
           return;
       }
           
           dtm.setRowCount(0);
      
           db.statement().executeUpdate("update other_exp set name='"+exp+"',date='"+date+"',time='"+time+"',amount='"+amount+"' where exp_id='"+int_id+"'");
            loadtable();
           JOptionPane.showMessageDialog(null,"Successfully Updated","Success Message",JOptionPane.INFORMATION_MESSAGE);
          
          
           auto_inc();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String id = jTextField1.getText();
       
        try {
             int i=0;
           ResultSet rs= db.statement().executeQuery("select exp_id from  other_exp");
           
           while(rs.next()){
               if(id.equals(rs.getString("exp_id"))){
                   i=i+1;
                   System.out.println(rs.getInt("exp_id"));
               }
           }
           if(i==0){
                JOptionPane.showMessageDialog(null,"No existing supply id for this number","Error Message",JOptionPane.ERROR_MESSAGE);
                return;
           }
           
            db.statement().executeUpdate("delete  from other_exp where exp_id="+id+" ");
            JOptionPane.showConfirmDialog(null,"Are you want to delete?", "Warning", i, JOptionPane.YES_NO_CANCEL_OPTION);
            loadtable();
            auto_inc();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String id= jTextField1.getText();
        jTextField3.setVisible(false);
            
        try {
            ResultSet rs= db.statement().executeQuery("select * from other_exp where exp_id='"+id+"'");
            while(rs.next()){
                jTextField2.setText(rs.getString("date"));
                jLabel9.setText(rs.getString("time"));
                jTextField6.setText(rs.getString("name"));
                
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        jTextField3.setVisible(true);
        String id= jTextField1.getText();
       
      
      
    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    public void loadtable() {
  
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        
        try {
            ResultSet rs= db.statement().executeQuery("select * from other_exp");
            
           while(rs.next()){
               Vector v = new Vector();
               v.add(rs.getInt(1));
               v.add(rs.getString(2));
               v.add(rs.getString(3));
               v.add(rs.getString(4));
               v.add(rs.getDouble(5));
               
               
               dtm.addRow(v);
               
              
                
            }
        
        } catch (Exception e) {
            e.printStackTrace();
        }  }

   
}
