/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Site_management;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author AKLive
 */
public class conall extends javax.swing.JPanel implements ActionListener{
    count c = new count();
    private JButton btn[] = new JButton[c.getcount()];
    String array[]=new String [c.getcount()];
   public static String num;
    /**
     * Creates new form conall
     */
    public conall() {
        initComponents();
           setSize(1370,620);
            BorderLayout b = new BorderLayout();
    FlowLayout f= new FlowLayout();
    GridLayout g = new GridLayout(4,2,4,4);
    GridLayout g2 = new GridLayout(2,3);
    
    setLayout(g);
    
        try {
            ResultSet rs= db.getconnection().createStatement().executeQuery(" select id,name from con_sites where compl_stat='on going' ");
            int i=0;
            String ns = " PROJECT";
            
            while(rs.next()){
                array[i] = rs.getString("id");
                btn[i]=new JButton(rs.getString("name").toUpperCase()+ns);
                btn[i].addActionListener(this);
                add(btn[i]);
                
                i++;        
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
      
    @Override
    
   
    public void actionPerformed(ActionEvent e) {
       Object src = e.getSource();
        for(int j=0;j<array.length;j++){
        if(src== btn[j]){
            num=array[j];
            System.out.println(num);
            System.out.println(array[j]);
           project_dashboards p = new project_dashboards();
           p.setVisible(true);
           
           
         }
        }
    }
}
