/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Site_management;


import java.awt.Image;
import java.awt.Label;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asbar Ali
 */
public class New_Project extends javax.swing.JInternalFrame {

    /**
     * Creates new form New_Project
     */
    public New_Project() {
        initComponents();
        ld_cus lc1 = new ld_cus();
        lc1.lc(jComboBoxcus);
       
    }
    
    public int random(){
    Random r =new Random();
       int i= r.nextInt(40000000)+90000000;
       return i;
    }
    
    public ImageIcon ResizeImage (String ImagePath,JLabel label){
        ImageIcon myimage = new ImageIcon(ImagePath);
        Image img = myimage.getImage();
        Image newimg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newimg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBoxcus = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1276, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("NEW PROJECT");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, -1));

        jLabel2.setText("Location/Area");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        jLabel1.setText("Project Name ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, 20));

        jLabel3.setText("Customer ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, 100));

        jLabel25.setText(":");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 10, 20));

        jLabel26.setText(":");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 10, -1));

        jLabel27.setText(":");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 10, -1));

        jLabel28.setText(":");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 10, -1));

        jComboBoxcus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcusActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1390, 520));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 120, 30));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reports"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 200, 210));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Special reports");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jLabel13.setText("Add CAD Drawing:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 60, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty-image.png"))); // NOI18N
        jLabel20.setText("Add Image here");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 190, 160));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 60, 20));

        jLabel12.setText("Add Project Image:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty-image.png"))); // NOI18N
        jLabel19.setText("Add Image here");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 190, 160));

        jLabel14.setText("Add Current Image:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, -1, -1));

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 60, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty-image.png"))); // NOI18N
        jLabel21.setText("Add Image here");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 190, 160));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setText(":");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 10, 20));

        jLabel11.setText("Actual Start Date  ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 20));
        jPanel4.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 200, -1));

        jLabel16.setText("Est. completion Date");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, 20));

        jLabel30.setText(":");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 10, 20));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, -1));

        jLabel5.setText("Status");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel29.setText(":");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 10, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVE", "INACTIVE", " " }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 75, 20));

        jLabel9.setText("Number of levels");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 20));

        jLabel32.setText(":");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 10, 20));

        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField7MouseEntered(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 200, -1));

        jLabel18.setText("Scale of cons.Area ");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 20));

        jLabel34.setText(":");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 10, 20));

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 200, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SquareKilometers[km2]", "SquareMeters[m2]", "SquareFeet[ft2]", "SquareYards[yd2]", "Acres[ac]", "Hectares[ha]" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 200, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 500));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Remarks:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 330, 160));

        jLabel7.setText("Construction Type");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jLabel35.setText(":");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 10, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apartment", "House", "Hotel", "Shop", "Other" }));
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 200, -1));

        jLabel8.setText("Construction Mode");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 20));

        jLabel31.setText(":");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 10, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "From begining", "Modification" }));
        jPanel5.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 200, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 390, 300));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 30));

        jButton10.setText("Select");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 30));

        jLabel15.setText("jLabel15");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 240, 300));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 120, 30));

        jLabel22.setText("jLabe22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 190, -1));

        jLabel23.setText("jLabel23");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 190, -1));

        jLabel24.setText("jLabel24");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 590));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        
        if( (jTextField1.getText().isEmpty()) ||(jTextField2.getText().isEmpty()) ||(jTextField7.getText().isEmpty()) ||(jTextField6.getText().isEmpty()) || (jDateChooser1.getDateFormatString().isEmpty()) || (jDateChooser2.getDateFormatString().isEmpty())   ){
        
         JOptionPane.showMessageDialog(null, "You Have Skipped Necessery Fields,please fill before proceed"); 
        
        }
        
        else{
        
        
        
       
        String name= jTextField1.getText();
        String area= jTextField2.getText();
        String Cust_id1= jComboBoxcus.getSelectedItem().toString();
        
        int Cust_id = Integer.parseInt(Cust_id1);
        
        String address= jTextArea2.getText();
        String status= jComboBox1.getSelectedItem().toString();
        String type= jComboBox2.getSelectedItem().toString();
        String mode= jComboBox3.getSelectedItem().toString();
        String levels= jTextField7.getText();
        String scl_sub1= jTextField6.getText();
        String scl_sub2= jComboBox4.getSelectedItem().toString();
        String scl= scl_sub1+" "+scl_sub2;
       
        String remarks=  jTextArea1.getText();
        
        String prgimg= jLabel22.getText();
        String cadimg= jLabel23.getText();
        String crimg= jLabel24.getText();
        
        cadimg= cadimg.replace("\\", "/");
        prgimg= prgimg.replace("\\", "/");
        crimg= crimg.replace("\\", "/");
       int random = random();
        
        Date d= jDateChooser1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date= sdf.format(d);
        
        Date d1= jDateChooser2.getDate();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String date1= sdf1.format(d1);
        
        Date d3 = new Date();
        SimpleDateFormat sdf3 = new SimpleDateFormat("yyyy-MM-dd");
        String today= sdf.format(d3);
        
        
        Vector v = new Vector();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int count= dtm.getRowCount();
        
        for(int ii=0;ii<count;ii++){
            v.add(dtm.getValueAt(ii, 0));
        }
        
        try {
            
            for(int j=0;j<count;j++){
                
                 String path= vs.get(j).toString();
                 path = path.replace("\\", "/");
                
            db.getconnection().createStatement().executeUpdate("insert into spc_report (id, name, img) values ('"+random+"','"+v.get(j)+"','"+path+"')");
            }
            
            db.getconnection().createStatement().executeUpdate("insert into con_sites ( id, name, location, cust_id, address, status, type,est_comp_date, mode, no_levels, scl_area, remarks,act_star_date,pro_img,3D_img) values ("+random+",'"+name+"','"+area+"','"+Cust_id+"','"+address+"','"+status+"','"+ type +"','"+ date +"', '"+ mode +"', '"+ levels +"', '"+ scl +"', '"+ remarks +"','"+ date1 +"','"+prgimg+"','"+cadimg+"')");
            
      
            db.getconnection().createStatement().executeUpdate(" insert into uimages (id,img,date) values('"+random+"','"+crimg+"','"+today+"'  ) ");
        
            JOptionPane.showMessageDialog(null,"Successfully Saved", "Success Message", JOptionPane.INFORMATION_MESSAGE );
            
            
              } 
        
                catch (Exception e) {
                 e.printStackTrace();
                 }
             this.setVisible(false);
            new Main_sites().setVisible(true);            
        }
         //this will close frame i.e. NewJFrame

            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

            JFileChooser file1 = new JFileChooser();
            FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
            "JPEG & GIF Images", "jpg", "gif");
            file1.setFileFilter(filter1);
            int result = file1.showSaveDialog(null);
            
            if (result == JFileChooser.APPROVE_OPTION){
            
                File selectedFile = file1.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                // type jlabel to show path
               
                JLabel label = jLabel19;
                
                jLabel22.setText(path);
                
                jLabel19.setIcon(ResizeImage(path, label));
                
                
            
            }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            JFileChooser file1 = new JFileChooser();
            FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
            "JPEG & GIF Images", "jpg", "gif");
            file1.setFileFilter(filter1);
            int result = file1.showSaveDialog(null);
            
            if (result == JFileChooser.APPROVE_OPTION){
            
                File selectedFile = file1.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
              
                
               
                JLabel label = jLabel20;
                
                
                jLabel20.setIcon(ResizeImage(path,label));
                jLabel23.setText(path);
            }
              
    }//GEN-LAST:event_jButton7ActionPerformed

    
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       JFileChooser file1 = new JFileChooser();
            FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
            "JPEG & GIF Images", "jpg", "gif");
            file1.setFileFilter(filter1);
            int result = file1.showSaveDialog(null);
            
            if (result == JFileChooser.APPROVE_OPTION){
            
                File selectedFile = file1.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                // type jlabel to show path
               
                JLabel label = jLabel21;
               
                jLabel21.setIcon(ResizeImage(path, label));
                jLabel24.setText(path);
            }
               
    }//GEN-LAST:event_jButton8ActionPerformed
//public String img1;
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       int i= jTable1.getSelectedRow();
        System.out.println(i);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.removeRow(i);
       
        
       
        
        
    }//GEN-LAST:event_jButton11ActionPerformed
    Vector vs = new Vector();
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        String name = jTextField8.getText();
        
        if(name.equals(null) || name.equals("")){
           JOptionPane.showMessageDialog(null,"Please Enter name first","Error Message", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
             JFileChooser file1 = new JFileChooser();
            FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
            "JPEG & GIF Images", "jpg", "gif");
            file1.setFileFilter(filter1);
            int result = file1.showSaveDialog(null);
            
            if (result == JFileChooser.APPROVE_OPTION){
            
                File selectedFile = file1.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                // type jlabel to show path
               
               
               
                jLabel15.setText(path);
               vs.add(path);
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                Vector v = new Vector();
                v.add(jTextField8.getText());
                dtm.addRow(v);
                
                
            
            }
        
        



    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBoxcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxcusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed

    char c = evt.getKeyChar();
  if ((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE))) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits(0-9)");
        
      
    }        


// TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed

    char c = evt.getKeyChar();
    if ((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE))) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits(0-9)");
        
      
    }        


// TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseEntered

        
         Date  rdate=jDateChooser1.getDate();
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy");
        String rdateY= sdm.format(rdate);
        SimpleDateFormat sdm1 = new SimpleDateFormat("MM");
        String rdateM= sdm1.format(rdate);
        SimpleDateFormat sdm2 = new SimpleDateFormat("dd");
        String rdateD= sdm2.format(rdate);
        System.out.println(rdateY+" "+rdateM+" "+rdateD);
        //----------------------------//
        Date  ddate=jDateChooser2.getDate();
        SimpleDateFormat sdm3 = new SimpleDateFormat("yyyy");
        String ddateY= sdm3.format(ddate);
        SimpleDateFormat sdm4 = new SimpleDateFormat("MM");
        String ddateM= sdm4.format(ddate);
        SimpleDateFormat sdm5 = new SimpleDateFormat("dd");
        String ddateD= sdm5.format(ddate);
        System.out.println(ddateY+" -  "+ddateM+" -  "+ddateD);
        int rdateYY=Integer.parseInt(rdateY);
        int rdateMM=Integer.parseInt(rdateM);
        int rdateDD=Integer.parseInt(rdateD);
          int ddateYY=Integer.parseInt(ddateY);
          int ddateMM=Integer.parseInt(ddateM);
          int ddateDD=Integer.parseInt(ddateD);
                  
                  
        if( (ddateYY >= rdateYY) && (ddateMM >= rdateMM) && (ddateDD > rdateDD) ){
        
       JOptionPane.showMessageDialog(null, "The completion date should be Later than start date");
            
        }
        else{
        
                
        System.out.println("lal");
                }



// TODO add your handling code here:
    }//GEN-LAST:event_jTextField7MouseEntered

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBoxcus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    
}
