/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Site_management;

import Software_Jframes.Finanace_reports;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author AKLive
 */
public class project_dashboards extends javax.swing.JFrame {

    /**
     * Creates new form project_dashboards
     */
    public project_dashboards() {
        initComponents();
        jLabel19.setText(conall.num);
        loaddata(); 
        loaddata2();
        loadtime();
        loadtime2();
        loadtime3();
        loadtcounts();
        loadsm();
        loadimg();
        getlevel_pay();
        
     //   loaddailycost();
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dat= sdf.format(d);
        
        setprg();
        project_cost p=new project_cost();
       
        jLabel13.setText( p.getToday_cost(jLabel19.getText(), dat)+"");
        jLabel24.setText(p.total_cost(jLabel19.getText())+"");
    }
    
     public int daysBetween(Date d1, Date d2){
             return (int)( (d2.getTime() - d1.getTime()) / (1000 * 60 * 60 * 24));
     }
  public ImageIcon ResizeImage (String ImagePath){
        ImageIcon Myimage = new ImageIcon(ImagePath); Image img = Myimage.getImage();
        Image newImg = img.getScaledInstance(jLabel42.getWidth(), jLabel42.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel422 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel40 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("ProjectID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 60, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("FAIRMOUNT PROJECT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 352, 55));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Status: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("-");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 10, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Current Session :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 294, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 138, 60, -1));

        jButton1.setText("Allocate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 130, -1));

        jButton3.setText("Subcontractors");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 431, 130, -1));

        jButton2.setText("Engineers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 431, 130, -1));

        jButton4.setText("View Cost History");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 222, 180, -1));

        jLabel34.setText(" :");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 111, 20, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty-image.png"))); // NOI18N
        jLabel41.setText("jLabel41");
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 470, 190, 160));

        jLabel422.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty-image.png"))); // NOI18N
        jLabel422.setText("jLabel41");
        jPanel1.add(jLabel422, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 190, 159));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty-image.png"))); // NOI18N
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 190, 160));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 255));
        jLabel44.setText("View Previous Images");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 640, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Location");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 111, 70, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("Duration");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 169, 70, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setText("Type ");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 201, 40, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setText("Mode  ");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 234, 60, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("Client info");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 77, 110, 20));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 51, 255));
        jLabel51.setText("Today's Cost : ");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 113, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("Cost until now :");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 139, 90, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("General Info");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 80, -1, -1));

        jLabel54.setText("Customer ID");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 108, 80, 20));

        jLabel57.setText("Contact");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 156, 46, 30));

        jButton9.setText("Email");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 222, 168, -1));

        jProgressBar2.setForeground(new java.awt.Color(0, 153, 0));
        jProgressBar2.setToolTipText("");
        jProgressBar2.setValue(50);
        jProgressBar2.setOpaque(true);
        jProgressBar2.setStringPainted(true);
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 386, 698, 39));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setText("Progress :");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 361, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(51, 51, 255));
        jLabel60.setText("Project Image");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 38, -1, 20));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(51, 51, 255));
        jLabel61.setText("3D Drawing");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 240, -1, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(51, 51, 255));
        jLabel62.setText("Current Situation");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, -1, 20));

        jLabel63.setText(" :");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 139, -1, -1));

        jLabel64.setText(" :");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 169, 20, -1));

        jLabel65.setText(" :");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 202, 20, -1));

        jLabel66.setText(" :");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 235, 20, -1));

        jLabel1.setText("Client name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 139, -1, -1));

        jLabel3.setText("E-Mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 192, -1, -1));

        jLabel4.setText(":");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 111, 14, -1));

        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 139, 14, -1));

        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 164, 14, -1));

        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 192, 14, -1));

        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 113, -1, -1));

        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 138, 328, 16));

        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 169, -1, -1));

        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 202, -1, -1));

        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 235, -1, -1));

        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 111, -1, -1));

        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 139, -1, -1));

        jLabel22.setText("jLabel22");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 164, -1, -1));

        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 192, -1, -1));

        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 114, -1, -1));

        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 139, -1, -1));

        jLabel25.setText("Complete Budget:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 192, 121, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Cost/Budget");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("154");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 296, -1, 47));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("Days Remaining");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 323, -1, -1));

        jLabel29.setText("jLabel29");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 192, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Contract Elapsed time");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 27, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("jLabel31");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 50, 90, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("jLabel35");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 124, 100, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Contract completion");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 99, 124, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Percent time elapsed");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 27, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("jLabel38");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Contract Start Date");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 101, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("N/A");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setText("Total Subcontractors");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 167, 140, -1));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(102, 102, 102));
        jLabel69.setText("jLabel69");
        jPanel2.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 121, 90, 30));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setText("Total Engineers ");
        jPanel2.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 167, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("N/A");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 190, 50, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("N/A");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 30));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setText("Total Supervisors");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel67.setText("Cons.Site Manager");
        jPanel2.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 231, 110, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(102, 102, 102));
        jLabel68.setText("No site manager");
        jPanel2.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 251, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 340, 300));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Update Project");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 220, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("View Map Loacation");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 220, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("View Custmer info");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 220, 40));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("View BOQ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 237, 40));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("View Spec Reports");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 237, 40));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Print Report");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 220, 40));

        jProgressBar1.setBackground(new java.awt.Color(0, 102, 255));
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 255));
        jProgressBar1.setValue(85);
        jProgressBar1.setString("50%");
        jPanel3.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 20));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Estimated and actual cost comaprison ");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 312, 21));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 720, 210));

        jLabel19.setText("ProjectID:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 80, 20));

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel71.setText(" ACTIVE");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 130, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 240, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 200, 20));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("LEVEL 03 ");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel73.setText("Electrical Works");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, 20));

        jButton5.setText("Supervisors");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 431, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        
        Update_project up = new Update_project();
        up.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       BOQ.another_new b = new BOQ.another_new();
       b.setVisible(true);
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        view_spec vs = new view_spec();
        vs.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        
        Allocate al = new Allocate();
        al.setVisible(true);

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        daily_project_cost dpc = new daily_project_cost();
        dpc.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        String URL ="https://www.google.lk/maps/place/";
        String place = jLabel14.getText();
        try {
             java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL+place));
        } catch (IOException ex) {
            Logger.getLogger(project_dashboards.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
       current_photos cr = new current_photos();
       cr.setVisible(true);
       
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
       current_photos cr = new current_photos();
       cr.setVisible(true);
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            vw_eng ve = new vw_eng();
            ve.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        vw_super vs = new vw_super();
        vs.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    reports fr = new reports();
    fr.setVisible(true);
    
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        subcontractor.another_new a = new subcontractor.another_new();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project_dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project_dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project_dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project_dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_dashboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel422;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        try {
            ResultSet rs= db.getconnection().createStatement().executeQuery("select * from con_sites where id = '"+ conall.num +"' and compl_stat = 'on going' ");
            while(rs.next()){
                
                   
                int lv1=(rs.getInt("com_lvls"));
                int lv2=lv1+1;
                
                jLabel72.setText("LEVEL    "+lv2);
                
                jLabel14.setText(rs.getString("location"));
              jLabel15.setText(rs.getString("address"));
           //   jLabel16.setText(rs.getString("address"));
              jLabel17.setText(rs.getString("type"));
              jLabel18.setText(rs.getString("mode"));
              jLabel71.setText(rs.getString("status"));
              jLabel73.setText(rs.getString("session"));
              
              String nm = (rs.getString("name").toUpperCase()); 
              
              jLabel5.setText(nm + " PROJECT");
              
              jLabel20.setText(rs.getString("Cust_id"));
              
              
              
              
              
              Date d= rs.getDate("est_comp_date");
              
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loaddata2() {
        
        int cusid=0;
        
         try {
            ResultSet rs88= db.getconnection().createStatement().executeQuery("select * from con_sites where id = '"+ conall.num +"'  ");
            if(rs88.next()){
                
                    String cusid1= rs88.getString("Cust_id");
                    cusid= Integer.parseInt(cusid1);
            }
            
            ResultSet rs99= db.getconnection().createStatement().executeQuery("select * from customer where Cust_id = '"+ cusid +"'  ");
           
            while(rs99.next()){
            
            jLabel20.setText(rs99.getString("Cust_id"));
            jLabel21.setText(rs99.getString("Name"));
            jLabel22.setText(rs99.getString("Telephone"));
            jLabel23.setText(rs99.getString("Email"));
                
            
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        
        
        
        
    }

    private void setprg() {
        
        try {
            float s=0;
        ResultSet rs55=    db.getconnection().createStatement().executeQuery(" select com_lvls from con_sites where id='"+conall.num+"' ");
            int intpass = Integer.parseInt(conall.num);
            if(rs55.next()){
            
               s= procount.unival(intpass,rs55.getInt("com_lvls"));
              jProgressBar2.setValue((int) s);
            }
          
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        
    }
    
private int getlevel(){
    int lv2=0;
    int lv1=0;
    try {
          ResultSet rs= db.getconnection().createStatement().executeQuery("select * from con_sites where id = '"+ conall.num +"' and compl_stat = 'on going' ");
            while(rs.next()){
                
                   
                lv1=(rs.getInt("com_lvls"));
                lv2=lv1+1;
            }
    } catch (Exception e) {
    }
    return lv2;
}
    
    private void loaddailycost() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String today= sdf.format(d);
        
        try {
            ResultSet rs= db.getconnection().createStatement().executeQuery("select sum(cost) from project_level_payment where date='"+today+"' and projectid='"+conall.num+"' ");
            
            if(rs.next()){
            
            jLabel13.setText(rs.getString("cost"));
                
            }
        
        
        
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    
    private void loadtime() {
        
        
        
        
        try {
            
            ResultSet rs78 = db.getconnection().createStatement().executeQuery(" select est_comp_date from con_sites where id='"+conall.num+"' ");
            
            if(rs78.next()){
            
                String comdate=(rs78.getString("est_comp_date"));
                
                 SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                
                  DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
	          //get current date time with Date()
	          Date date = new Date();
	  
      
           
                 String s=(dateFormat.format(date));
                 
                 
                 
                 Date d11=null;
                 Date d2=null;                
                 try {
            
                                        d11 = format.parse(comdate);
                                        d2 = format.parse(s);
            
            
            
            
            
                                  } catch (Exception e) {
                                      e.printStackTrace();
                                          }
                
                       long diff =  (d11.getTime() - d2.getTime());
                       long diffdys = diff / (1000 * 60 * 60 * 24);
                       
                       int d1111= (int) (diffdys);
                       
                      
                       
                      jLabel27.setText(""+d1111);
                       
                       
                       
                       
            }
            
            
        } catch (Exception e) {
        }
        
        
        
        
    }

    int perc=0;
    private void loadtime2() {
        
        try {
            
             ResultSet rs79 = db.getconnection().createStatement().executeQuery(" select act_star_date from con_sites where id='"+conall.num+"' ");
            
            if(rs79.next()){
            
                    
                    String stardate=(rs79.getString("act_star_date"));
                
                 SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                
                  DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
	          //get current date time with Date()
	          Date date = new Date();
	  
      
           
                 String s=(dateFormat.format(date));
                 
                 
                 
                 Date d11=null;
                 Date d2=null;                
                 try {
            
                                        d11 = format.parse(stardate);
                                        d2 = format.parse(s);
            
            
            
            
            
                                  } catch (Exception e) {
                                      e.printStackTrace();
                                          }
                
                       long diff =  (d2.getTime() - d11.getTime());
                       long diffdys = diff / (1000 * 60 * 60 * 24);
                       
                       int d1111= (int) (diffdys);
                       
                      
                       perc=d1111;
                      jLabel31.setText(d1111+" days");
                       
            
            
            }
             
        
        
        } catch (Exception e) {
        }
        
        
        
    }

    private void loadtime3() {
        
        try {
            
            ResultSet rs91 = db.getconnection().createStatement().executeQuery(" select * from con_sites where id='"+conall.num+"' ");
            
            while(rs91.next()){
            
            String comdate=(rs91.getString("est_comp_date"));
            String stardate= (rs91.getString("act_star_date"));
            jLabel35.setText(comdate);
            jLabel69.setText(stardate);
            
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            
            
            
            Date d1=null;
            Date d2=null;
            
                try {
                    
                    d2 = format.parse(comdate);
                    d1 = format.parse(stardate);
                    
                    
                 
                    
                    
                } catch (Exception e) {
                }
            
            
            
            
                
                       long diff =  (d2.getTime() - d1.getTime());
                       long diffdys = diff / (1000 * 60 * 60 * 24);
                       
                       int d1111= (int) (diffdys);
                       
                      
                       
                      jLabel16.setText(d1111+" days");
            
                      float pcntg= (perc *100)/d1111;
                      
                      jLabel38.setText(pcntg+"%");
            
            
            
            
            
            
            }
            
            
            
            
            
            
        } catch (Exception e) {
        }
        
    }

    private void loadsm() {
        
           int siteman=0;
      try{  
        ResultSet rs77= db.getconnection().createStatement().executeQuery("select * from con_sites where id = '"+ conall.num +"' ");
     
       if(rs77.next()){
        String sitman1 = (rs77.getString("Site_manager"));
        
          
      
        siteman= Integer.parseInt(sitman1);
        
       }
        ResultSet rs777= db.getconnection().createStatement().executeQuery("select * from employee where idemployee = '"+ siteman +"' ");
        
        while(rs777.next()){
        String fname77= (rs777.getString("fname"));
        String lname77= (rs777.getString("lname"));
        
        String name= fname77+" "+lname77;
        
        jLabel68.setText(name);
       
        }
      
      }catch(Exception e5){
          e5.printStackTrace();
      }
        
        
        
        
    }

    private void loadtcounts() {
       int size = 0;
       int size2 = 0;
        try {
            
           ResultSet r1 = db.getconnection().createStatement().executeQuery(" SELECT * FROM assinged_sup WHERE id='"+conall.num+"' ");
           
           
           
            r1.last();
            size = r1.getRow();
            r1.beforeFirst();

           
           
           jLabel47.setText(""+size);
            
        
           ResultSet r2 = db.getconnection().createStatement().executeQuery(" SELECT * FROM assinged_eng WHERE id='"+conall.num+"' ");
        
            r2.last();
            size2 = r2.getRow();
            r2.beforeFirst();

           
           
           jLabel33.setText(""+size2);
        
        
        
        
        
        
        } catch (Exception e) {
        }
        
    }

    private void loadimg() {
        
        try {
            
            ResultSet rs45= db.getconnection().createStatement().executeQuery("select * from con_sites where id = '"+ conall.num +"' ");
            while(rs45.next()){
            
            String primg= rs45.getString("pro_img");
                
             //   String primg=("C:\\Users\\AKLive\\Pictures\\ConvergeUI.jpg");
              //  System.out.println(primg);
            jLabel422.setIcon(ResizeImage(primg));
            
            String cadimg= rs45.getString("3D_img");
                System.out.println(cadimg);
            jLabel42.setIcon(ResizeImage(cadimg));
            
            
            
            
            
            
            }
            
            
            ResultSet rs46= db.getconnection().createStatement().executeQuery("select img from uimages where id = '"+ conall.num +"' ");
            
            while(rs46.next()){
            
             String cr1=rs46.getString("img");
                
            jLabel41.setIcon(ResizeImage(cr1));
                
            
            }
            
            
            
            
        } catch (Exception e) {
        }
        
        
        
        
        
       
    }
    public double get_budget(){
        double numa=0.0;
        try {
            ResultSet rs= db.getconnection().createStatement().executeQuery("select Total_amount from boq where Project_name='"+conall.num+"'");
            while(rs.next()){
              numa =numa+ rs.getDouble("Total_amount");
            }
            
        } catch (Exception e) {
        }
        return numa;
    }

    private void getlevel_pay() {
       
        int sum=0;
        try {
            ResultSet rs= db.getconnection().createStatement().executeQuery("select cost from project_level_payment where  projectid='"+conall.num+"'");
            while(rs.next()){
                sum=sum+Integer.parseInt(rs.getString("cost"));
        }
            
            System.out.println(sum+"sdfjhsif");
            System.out.println(get_budget());
            System.out.println("ela");
            
            int differ = (int) ((sum/get_budget())*100);
            jProgressBar1.setValue(differ);
            System.out.println(differ);
            
            
        } catch (Exception e) {
        }
    }
}
