/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import test_new.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

 

    
/**
 *
 * @author SANDEEPA-PC
 */
public class aggree extends javax.swing.JInternalFrame {
    private String string;
    

    public aggree() {
        initComponents();
                    
        Random ran = new Random();
        int n=ran.nextInt(5000)+7;
        jLabel9.setText(n+"");
       
           
    }
    
    public ImageIcon ResizeImage(String ImagePath) { 
        ImageIcon MyImage = new ImageIcon(ImagePath); Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel17.getWidth(), jLabel17.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg); 
        return image;
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Customer ID ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setText("Contract Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setText("Estimate Settelement Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 20));

        jLabel6.setText("Contract Signed Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel7.setText("Owner Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setText("Rough BOQ (Rs)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Agree_ID", "proID", "Cus_ID", "Con_Sign", "Est_date", "Con_date", "Duration", "Base_price", "BOQ", "Amount", "Tot_base", "Cont_type", "Con_name", "Owner", "Address", "Sign"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 1250, 100));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 120, -1));

        jLabel12.setText("Duration");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel13.setText("Agreement ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "001", "002", "003", "004", "005", "006", "007", "008" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 20));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 200, 20));

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField15MouseEntered(evt);
            }
        });
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 200, 20));

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 120, 30));

        jButton7.setText("Print report");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 310, 120, 30));

        jButton8.setText("Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 30));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, 120, 100));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 200, 70));

        jLabel15.setText("Base Price (Rs)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jLabel18.setText("Other Amount (Rs)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        jLabel19.setText("Contacter Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel20.setText("Total Base (Rs)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        jLabel21.setText("Address ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jLabel22.setText("Contrac Type");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 200, -1));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 200, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 200, -1));

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 200, -1));

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, -1));

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 200, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 200, -1));

        jLabel16.setText("project ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, -1));

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 200, 20));

        jButton3.setText("Signature");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, 120, 30));

        jDateChooser3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateChooser3MouseEntered(evt);
            }
        });
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 200, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 200, 20));

        jLabel14.setText("Agreement ID :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 200, 20));
        jTextField7.getAccessibleContext().setAccessibleDescription("");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Agreement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(604, 604, 604)
                .addComponent(jLabel1)
                .addContainerGap(649, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1330, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("View Agreement Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(604, 604, 604)
                .addComponent(jLabel2)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1330, -1));

        jToggleButton1.setText("View");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 
        int r =jTable1.getSelectedRow();
        jLabel9.setText(jTable1.getValueAt(r,0).toString());        
        jComboBox1.setSelectedItem(jTable1.getValueAt(r,1).toString());
        jTextField3.setText(jTable1.getValueAt(r,2).toString());
        String s1 = (jTable1.getValueAt(r,15).toString());
        jLabel17.setIcon(ResizeImage(s1));
        
          String string= jTable1.getValueAt(r,3).toString();
       
            try {
            DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
             Date date3  = format.parse(string);
             jDateChooser2.setDate(date3);
             } catch (Exception e) {
             e.printStackTrace();
        }
        
         String string1= jTable1.getValueAt(r,4).toString();
              try {
              DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
              Date date1  = format.parse(string);
              jDateChooser1.setDate(date1);
              } catch (Exception e) {
              e.printStackTrace();
        }
        
         String string2 = jTable1.getValueAt(r,5).toString();
              try {
              DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
              Date date5  = format.parse(string);
              jDateChooser3.setDate(date5);
              } catch (Exception e) {
              e.printStackTrace();
        }
        

         
        
        jTextField15.setText(jTable1.getValueAt(r,6).toString());
        jTextField16.setText(jTable1.getValueAt(r,7).toString());
        jTextField11.setText(jTable1.getValueAt(r,8).toString());
        jTextField12.setText(jTable1.getValueAt(r,9).toString());
        jTextField13.setText(jTable1.getValueAt(r,10).toString());
        jTextField18.setText(jTable1.getValueAt(r,12).toString());
        jTextField17.setText(jTable1.getValueAt(r,11).toString());
        jTextField14.setText(jTable1.getValueAt(r,13).toString());
        jTextArea1.setText(jTable1.getValueAt(r,14).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String Agg_id = jLabel9.getText();
  
        if(Agg_id.equals("")|| Agg_id == null){
          JOptionPane.showMessageDialog(null, "Please enter the Agreement ID","Error in Registration", JOptionPane.ERROR_MESSAGE);
          return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
        if(x==0){
       
              try {
                com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getconnection().createStatement();
                st.executeUpdate("DELETE from cus_agreement where id='"+Agg_id+"'");
                tableload(Agg_id);
              } catch (Exception e) {
                e.printStackTrace();
           }
       }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    
      
        String Agg_id = jLabel9.getText();    
        String projs_id = (String) jComboBox1.getSelectedItem();
        String cuss_id = jTextField3.getText();
         
        Date ests_settelement=jDateChooser1.getDate();
        Date contrc_date=jDateChooser2.getDate();
        Date contrs_signed=jDateChooser3.getDate();
         
        String durations = jTextField15.getText();
        String bases_price = jTextField16.getText();
        String roughs_boq = jTextField11.getText();
        String others_amount = jTextField12.getText();
        String tots_base = jTextField13.getText();
        String contrs_type = jTextField18.getText();
        String contrs_name = jTextField17.getText();
        String owners_name = jTextField14.getText();
        String addrss = jTextArea1.getText();
        String signs = jLabel17.getText();
       
         
         
         
         if(Agg_id.equals("")|| Agg_id == null){
            JOptionPane.showMessageDialog(null,"Please Search and enter the AgreementID","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        
        tableload(Agg_id); 
       
        
                 if (durations.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Contract Duration","Error in Duration",JOptionPane.ERROR_MESSAGE);
                else if (contrs_type.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Contractor Type","Error in Contractor Type",JOptionPane.ERROR_MESSAGE);
              
                else if (contrs_name.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Contractor Name","Error in Contractor Name",JOptionPane.ERROR_MESSAGE);
                
                else if (owners_name.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Owner Name","Error in Owner Name",JOptionPane.ERROR_MESSAGE);
                
                else if (addrss.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Address","Error in Address",JOptionPane.ERROR_MESSAGE);
                
               
                
           
          
        
   
         try {
             Statement st= db.getconnection().createStatement();
            st.executeUpdate("update cus_agreement set id='"+Agg_id+"',  proj_id ='"+ projs_id +"',cus_id='"+cuss_id+"',contr_date='"+contrc_date +"',est_settelement='"+ ests_settelement +"', contr_signed='"+ contrs_signed+"',duration='"+durations +"',base_price='"+ bases_price+"',rough_boq='"+roughs_boq+"',other_amount='"+others_amount+"',tot_base='"+tots_base+"',  contr_type='"+  contrs_type+"',contr_name='"+contrs_name+"',owner_name='"+owners_name+"',addrs='"+addrss+"',sign='"+signs+"' where id='"+  Agg_id +"'");
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                              
              JOptionPane.showMessageDialog(null,"Successfully Update,,,"); 
              
            jTextField3.setText(null);
            jDateChooser2.setDate(null);
            jDateChooser1.setDate(null);
            jDateChooser3.setDate(null);
            jTextField15.setText(null);
            jTextField16.setText(null);
            jTextField11.setText(null);
            jTextField12.setText(null);
            jTextField13.setText(null);
            jTextField17.setText(null);
            jTextField18.setText(null);
            jTextField14.setText(null);
            jTextArea1.setText(null);
             
        } catch (Exception e) {
            e.printStackTrace();
        }

        
        
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
         tableload(Agg_id); 



     
        
        


 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try {
            String filename=chooseFile();
            
        Document document=new Document(); 
        PdfWriter.getInstance(document,new FileOutputStream(filename+".pdf"));
          document.open();
          document.add(new Paragraph("----------------------------------------View Customer Payment----------------------------------------")); 
          document.add(new Paragraph(" ")); 
           
             
          document.add(new Paragraph("Project ID               :"+jLabel9.getText())); 
          document.add(new Paragraph("Project ID               :"+jComboBox1.getSelectedItem()));
          document.add(new Paragraph("Customer ID              :"+jTextField3.getText())); 
          document.add(new Paragraph("Contractor Name          :"+jTextField18.getText()));  
          document.add(new Paragraph("Owner Name               :"+jTextField14.getText())); 
          document.add(new Paragraph("Contract Type            :"+jTextField17.getText())); 
          document.add(new Paragraph("Contract Date            :"+jDateChooser2.getDate())); 
          document.add(new Paragraph("Estimate Settelement Date:"+jDateChooser1.getDate())); 
          document.add(new Paragraph("Contract Signed Date     :"+jDateChooser3.getDate()));  
          document.add(new Paragraph("Duration                 :"+jTextField15.getText())); 
          document.add(new Paragraph("Rough BOQ Price          :"+jTextField11.getText())); 
          document.add(new Paragraph("Base Price               :"+jTextField16.getText())); 
          document.add(new Paragraph("Other Amount             :"+jTextField12.getText())); 
          document.add(new Paragraph("Total Base Price         :"+jTextField13.getText())); 
          document.add(new Paragraph("Address                  :"+jTextArea1.getText())); 
          document.add(new Paragraph("Image                    :"+jLabel7.getText())); 
           document.close();
        JOptionPane.showMessageDialog(null,"Successfully Created.");
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,"you have not create any file");
        }         // 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    
         
        String Agg_id = jLabel9.getText();    
        String projs_id = (String) jComboBox1.getSelectedItem();
        String cuss_id = jTextField3.getText();
       
      Date date1=jDateChooser1.getDate();
         
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String ests_settelement= sdf.format(date1);
       
      Date date3=jDateChooser2.getDate();
         
           SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
           String contrc_date = sdf1.format(date3);
       
      Date date5=jDateChooser3.getDate();
         
          SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
          String contrs_signed= sdf2.format(date5);
    
        String durations = jTextField15.getText();
        String bases_price = jTextField16.getText();
        String roughs_boq = jTextField11.getText();
        String others_amount = jTextField12.getText();
        String tots_base = jTextField13.getText();
        String contrs_type = jTextField17.getText();
        String contrs_name = jTextField18.getText();
        String owners_name = jTextField14.getText();
        String addrss = jTextArea1.getText();
        String signs = jLabel17.getText();
       
        Random ran = new Random();
        int n=ran.nextInt(5000)+7;
        jLabel9.setText(n+"");
       
                
                 if (durations.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Contract Duration","Error in Duration",JOptionPane.ERROR_MESSAGE);
                else if (contrs_type.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Contractor Type","Error in Contractor Type",JOptionPane.ERROR_MESSAGE);
              
                else if (contrs_name.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Contractor Name","Error in Contractor Name",JOptionPane.ERROR_MESSAGE);
                
                else if (owners_name.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Owner Name","Error in Owner Name",JOptionPane.ERROR_MESSAGE);
                
                else if (addrss.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Address","Error in Address",JOptionPane.ERROR_MESSAGE);
                
               
                
           
          
        

                else{
             
        try {
            
             signs = signs.replace("\\","/");
            
            Statement st= db.getconnection().createStatement();
            st.executeUpdate("Insert into cus_agreement(id, proj_id, cus_id, contr_date, est_settelement, contr_signed, duration, base_price, rough_boq, other_amount, tot_base, contr_type, contr_name, owner_name, addrs, sign) values('"+ Agg_id +"','"+ projs_id+"','"+cuss_id +"','"+ contrc_date +"','"+  ests_settelement +"','"+contrs_signed+"','"+ durations+"','"+  bases_price +"','"+roughs_boq+"','"+others_amount+"','"+ tots_base+"','"+contrs_type +"','"+ contrs_name+"','"+owners_name +"','"+ addrss+"','"+signs+"')");
            JOptionPane.showMessageDialog(null,"Successfully Saved,,,");
            jTextField3.setText(null);
            jDateChooser2.setDate(null);
            jDateChooser1.setDate(null);
            jDateChooser3.setDate(null);
            jTextField15.setText(null);
            jTextField16.setText(null);
            jTextField11.setText(null);
            jTextField12.setText(null);
            jTextField13.setText(null);
            jTextField17.setText(null);
            jTextField18.setText(null);
            jTextField14.setText(null);
            jTextArea1.setText(null);
            
            
           
            
            
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            tableload();
            
               
 
        } catch (Exception e) {
            e.printStackTrace();
        }
            
      
                                        

            
                }            
                 
      
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           
JFileChooser file = new JFileChooser();
           FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
           file.setFileFilter(filter);
           int result = file.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel17.setText(path);
            jLabel17.setIcon(ResizeImage(path));
        }
 
    // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseEntered
Date  rdate=jDateChooser2.getDate();
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy");
        String rdateY= sdm.format(rdate);
        SimpleDateFormat sdm1 = new SimpleDateFormat("MM");
        String rdateM= sdm1.format(rdate);
        SimpleDateFormat sdm2 = new SimpleDateFormat("dd");
        String rdateD= sdm2.format(rdate);
        System.out.println(rdateY+" "+rdateM+" "+rdateD);
        //----------------------------//
        Date  ddate=jDateChooser3.getDate();
        SimpleDateFormat sdm3 = new SimpleDateFormat("yyyy");
        String ddateY= sdm3.format(ddate);
        SimpleDateFormat sdm4 = new SimpleDateFormat("MM");
        String ddateM= sdm4.format(ddate);
        SimpleDateFormat sdm5 = new SimpleDateFormat("dd");
        String ddateD= sdm5.format(ddate);
        System.out.println(ddateY+" -  "+ddateM+" -  "+ddateD);
        int rdateYY=Integer.parseInt(rdateY);
        int rdateMM=Integer.parseInt(rdateM);
        int rdateDD=Integer.parseInt(rdateD);
          int ddateYY=Integer.parseInt(ddateY);
          int ddateMM=Integer.parseInt(ddateM);
          int ddateDD=Integer.parseInt(ddateD);
                  
                  
        if( (ddateYY >= rdateYY) && (ddateMM >= rdateMM) && (ddateDD > rdateDD) ){
        
        System.out.println("lol1");
        }
        else{
        JOptionPane.showMessageDialog(null,"Please Enter the current Date","Error in Date",JOptionPane.ERROR_MESSAGE);
                
       
                }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15MouseEntered

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String agg = jTextField7.getText();
        if (agg.equals("") || agg == null) {
            JOptionPane.showMessageDialog(null, "Please Enter the Customer ID", "Error in Cus_ID", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            tableload(agg);
        }//    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
       
        
        char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits");
        
      
    }
        
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
      
        
        
        char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits");
        
      
    }
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
    
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
        
       } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits(0-9)");
        
      
    }
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
          char c = evt.getKeyChar();
          if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter Only Digits");
        
      
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
  char c =evt.getKeyChar();
  if(Character.isDigit(c)){


}else{
         JOptionPane.showMessageDialog(null, "Enter only Numeric Digits");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed

        
        
        
       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jDateChooser3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser3MouseEntered
Date  rdate=jDateChooser2.getDate();
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy");
        String rdateY= sdm.format(rdate);
        SimpleDateFormat sdm1 = new SimpleDateFormat("MM");
        String rdateM= sdm1.format(rdate);
        SimpleDateFormat sdm2 = new SimpleDateFormat("dd");
        String rdateD= sdm2.format(rdate);
        System.out.println(rdateY+" "+rdateM+" "+rdateD);
        //----------------------------//
        Date  ddate=jDateChooser1.getDate();
        SimpleDateFormat sdm3 = new SimpleDateFormat("yyyy");
        String ddateY= sdm3.format(ddate);
        SimpleDateFormat sdm4 = new SimpleDateFormat("MM");
        String ddateM= sdm4.format(ddate);
        SimpleDateFormat sdm5 = new SimpleDateFormat("dd");
        String ddateD= sdm5.format(ddate);
        System.out.println(ddateY+" -  "+ddateM+" -  "+ddateD);
        int rdateYY=Integer.parseInt(rdateY);
        int rdateMM=Integer.parseInt(rdateM);
        int rdateDD=Integer.parseInt(rdateD);
          int ddateYY=Integer.parseInt(ddateY);
          int ddateMM=Integer.parseInt(ddateM);
          int ddateDD=Integer.parseInt(ddateD);
                  
                  
        if( (ddateYY >= rdateYY) && (ddateMM >= rdateMM) && (ddateDD > rdateDD) ){
        
        System.out.println("lol1");
        }
        else{
        JOptionPane.showMessageDialog(null,"Please Enter the current Date","Error in Date",JOptionPane.ERROR_MESSAGE);
                
       
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser3MouseEntered

    private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
      
        
        char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits");
        
      
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16KeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        tableload();
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

     private String chooseFile() {
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename =f.getAbsolutePath();
        return filename;
    }
    
    private void tableload() {
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
           dtm.setRowCount(0);
         try {
            
               ResultSet rs= db.getconnection().createStatement().executeQuery("select * from  cus_agreement");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("id"));
            v.add(rs.getString("proj_id"));
            v.add(rs.getString("cus_id"));
            v.add(rs.getString("contr_date"));
            v.add(rs.getString("est_settelement"));
            v.add(rs.getString("contr_signed"));
            v.add(rs.getString("duration"));
            v.add(rs.getString("base_price"));
            v.add(rs.getString("rough_boq"));
            v.add(rs.getString("other_amount"));
            v.add(rs.getString("tot_base"));
            v.add(rs.getString("contr_type"));
            v.add(rs.getString("contr_name"));
            v.add(rs.getString("owner_name")); 
            v.add(rs.getString("addrs")); 
            v.add(rs.getString("sign"));
           
                 
               
             dtm.addRow(v);
      
           }
    }
         catch(Exception e){
         e.printStackTrace();
    }
    }       
    
         


    private void tableload(String id) {
                  DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
           dtm.setRowCount(0);
         try {
            
              
                  ResultSet rs= db.getconnection().createStatement().executeQuery("select * from cus_agreement where id Like'%"+id+"%'");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("id"));
            v.add(rs.getString("proj_id"));
            v.add(rs.getString("cus_id"));
            v.add(rs.getString("contr_date"));
            v.add(rs.getString("est_settelement"));
            v.add(rs.getString("contr_signed"));
            v.add(rs.getString("duration"));
            v.add(rs.getString("base_price"));
            v.add(rs.getString("rough_boq"));
            v.add(rs.getString("other_amount"));
            v.add(rs.getString("tot_base"));
            v.add(rs.getString("contr_type"));
            v.add(rs.getString("contr_name"));
            v.add(rs.getString("owner_name")); 
            v.add(rs.getString("addrs")); 
            v.add(rs.getString("sign"));
           
                 
               
             dtm.addRow(v);
      
           }
    }
         catch(Exception e){
         e.printStackTrace();
        
    }
    }}

  
     
    
