/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package subcontractor;

import test_new.*;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author westlifzzz
 */
public class add_dailyinfo extends javax.swing.JFrame {

    /**
     * Creates new form add_dailyinfo
     */
    public add_dailyinfo() {
        initComponents();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String frmtdDate = dateFormat.format(date);
        
        jLabel17.setText(frmtdDate);
        
        tableload();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 20));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, 30));

        jLabel2.setText("ScID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ScID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, -1));

        jLabel7.setText("TASK NAME");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, -1));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 20));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, 20));

        jLabel12.setText("SITE NAME");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 70, -1));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 90, 20));

        jLabel14.setText("PROJECT ID");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 80, -1));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 480, 130));

        jLabel4.setText("DESCRIPTION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel10.setText("UPLOAD IMAGES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 100, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 210, 110));

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 140, 30));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 170, 100));

        jButton6.setText("Browse");
        jButton6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jButton6AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 140, 30));

        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ScID", "TASK NAME", "SITE NAME", "PROJECT ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 460, 130));

        jLabel16.setText("Date");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 50, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton6AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6AncestorMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & GIF Images", "jpg", "gif");
        file.setFileFilter(filter);
        int result = file.showSaveDialog(null);

        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel6.setText(path);
           jLabel6.setIcon(ResizeImage(path)); }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       String sub_id = jLabel5.getText();
        if(sub_id.equals("")|| sub_id.equals(null)){
           JOptionPane.showMessageDialog(null, "Please enter the Sub-contractor ID","Error in Sc_ID", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getConnection().createStatement();
               st.executeUpdate("DELETE from sub_daily_progress where SC_id='"+sub_id+"'");
              // DELETE FROM somelog WHERE user = 'jcole'
               jLabel5.setText(null);
           
            
           
            jLabel9.setText(null);
            jLabel13.setText(null);
            jLabel15.setText(null);
            jTextArea1.setText(null);
            jLabel6.setIcon(null);
            jLabel6.setText(null);
               
           } catch (Exception e) {
               e.printStackTrace();
           }
           
    }                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String sub_id =jLabel5.getText();
        String specail =jLabel9.getText();
        String site_name =jLabel13.getText();
        
        String desc =jTextArea1.getText();
        String image=jLabel6.getText();
        
        String date=jLabel17.getText();
        
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        Date date = new Date();
//        String frmtdDate = dateFormat.format(date);

        //System.out.println("frmtdDate: " + frmtdDate);
        image = image.replace("\\","/");
        if(desc.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Descrption");
            
        }
        else{
            try {
            Statement st= db.getConnection().createStatement();
            st.executeUpdate("Insert into sub_daily_progress( Date, SC_id, Specialization, Site_name, Description, Images) values('"+date+"','"+ sub_id+"','"+specail+"','"+site_name+"','"+desc+"','"+image+"')");
            JOptionPane.showMessageDialog(null,"Successfully Saved...!!");
            
            jLabel5.setText(null);
            jLabel9.setText(null);
            jLabel13.setText(null);
            jTextArea1.setText(null);
            jLabel6.setIcon(null);
            jLabel15.setText(null);
            jLabel6.setText(null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
      }  
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sub_id=jTextField1.getText();
        if(sub_id.equals("") || sub_id.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Subcontractor id","Error in sub_id",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
           tableloadsearch(sub_id); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r =jTable1.getSelectedRow();
        jLabel5.setText(jTable1.getValueAt(r, 0).toString());
        jLabel9.setText(jTable1.getValueAt(r, 1).toString());
        
        jLabel13.setText(jTable1.getValueAt(r, 2).toString());
        jLabel15.setText(jTable1.getValueAt(r, 3).toString());
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_dailyinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_dailyinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_dailyinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_dailyinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_dailyinfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

private Icon ResizeImage(String path) {
       ImageIcon MyImage = new ImageIcon(path); Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg); 
        return image; 
    }


void tableloadsearch(String sub_id){
    
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
       //     ResultSet rs= db.getConnection().createStatement().executeQuery("select * from task_allocate INNER JOIN sub_daily_progress ON SC_id=sub_id where SC_id='"+sub_id+"'");
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from sub_daily_progress INNER JOIN task_allocate ON sub_id=SC_id where sub_id like '%"+sub_id+"%'");
//            ResultSet rs2= db.getConnection().createStatement().executeQuery("select * from task_allocate where sub_id Like'%"+sub_id+"%'");
              while(rs.next()){  
                Vector v = new Vector();
                v.add(rs.getString("SC_id"));
     //            v.add(rs.getString("Allocated_task"));
                v.add(rs.getString("Specialization"));
                v.add(rs.getString("Site_name"));
                
                
                v.add(rs.getString("pro_id"));
                
            
            dtm.addRow(v);

              
              }

        
        }catch(Exception e){
            e.printStackTrace();
        }
}

public void tableload(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         try {
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from sub_daily_progress INNER JOIN task_allocate ON sub_id=SC_id");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("SC_id"));
            v.add(rs.getString("Specialization"));
            v.add(rs.getString("Site_name"));
            v.add(rs.getString("pro_id"));
            
            
             dtm.addRow(v);
      
           }
    }
         catch(Exception e){
         e.printStackTrace();
         
         }

}

}
