/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package subcontractor;

import test_new.*;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author westlifzzz
 */
public class sub_agreement extends javax.swing.JInternalFrame {

    /**
     * Creates new form sub_agreement
     */
    public sub_agreement() {
        initComponents();
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
         tableload();
         sign_combo();
         
//         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        Date date = new Date();
//        String frmtdDate = dateFormat.format(date);
//        
//        jLabel5.setText(frmtdDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1340, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sub-contractor Agreement");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 14, 190, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 50));

        jLabel1.setText("Search by Agreement ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, 20));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 150, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Agree_no", "Desc", "Sign_Date", "Signed_by", "Estimate_Sett", "Add_want", "image"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1190, 100));

        jLabel3.setText("Sign Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 90, 20));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 70, -1));

        jLabel6.setText("Estimate Settelment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 200, -1));

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 140, 30));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseReleased(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 200, -1));

        jLabel7.setText("Agreement ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 80, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 200, -1));

        jLabel8.setText("Signed by");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 90, 20));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 200, 20));

        jLabel9.setText("Description");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 80, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 200, 80));

        jLabel11.setText("Additional wants");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 100, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 200, 80));

        jLabel12.setText("Image of Agreement ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 120, 20));

        jButton6.setText("Browse");
        jButton6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jButton6AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 270, 140, 30));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 410, 200));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 140, 30));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 140, 30));

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 140, 30));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 140, 30));

        jButton4.setText("print Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Icon ResizeImage(String path) {
       ImageIcon MyImage = new ImageIcon(path); Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg); 
        return image; 
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            String agree_no=jTextField1.getText();
        if(agree_no.equals("") || agree_no.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the agreement no","Error in agree_no",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
           tableload_search(agree_no); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton6AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6AncestorMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & GIF Images", "jpg", "gif");
        file.setFileFilter(filter);
        int result = file.showSaveDialog(null);

        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel13.setText(path);
            jLabel13.setIcon(ResizeImage(path));
        
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        String agree_no=jTextField3.getText();
        if(duplicatesAgreeno()){
            return;
        }
         String desc=jTextArea1.getText();
         
         Date signdate=jDateChooser1.getDate();
         SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
         String date= sdm.format(signdate);
         
     //    String contr_sign = null;
            
//         if(jRadioButton1.isSelected()){
//               contr_sign="Yes";
//           }else{
//               contr_sign="No";
//           }
         
     
         String sign_by=jComboBox1.getSelectedItem().toString();
         String estset=jTextField2.getText();
         String add_want=jTextArea2.getText();
         String image=jLabel13.getText();
         
         
         image = image.replace("\\","/");
         
          if (agree_no.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Agreement No");
          
          else if (desc.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Descriptions");
          
          else if (estset.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Estimate Settlement");
               
            
          else{    
                     try {
                         
            Statement st= db.getConnection().createStatement();
            st.executeUpdate("Insert into sub_contractor_agreement(Id_sub,descrp,Contract_date, signby,Est_settelment,addit_want, image) values('"+agree_no +"','"+desc +"','"+ date+"','"+sign_by+"','"+estset+"','"+add_want+"','"+image+"')");
            JOptionPane.showMessageDialog(null,"Successfully Saved...!");
            
            jTextField3.setText(null);
            jTextArea1.setText(null);
            jDateChooser1.setDate(null);
            jComboBox1.setSelectedIndex(0);
            jTextField2.setText(null);
            jTextArea2.setText(null);
            jLabel13.setIcon(null);
            jLabel13.setText(null);
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
         tableload();
         
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int r =jTable1.getSelectedRow();
        
        jTextField3.setText(jTable1.getValueAt(r,0).toString());
        jTextArea1.setText(jTable1.getValueAt(r,1).toString());
       
         String start_date=jTable1.getValueAt(r,2 ).toString();
        try{
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date1=format.parse(start_date);
            jDateChooser1.setDate(date1);
        }catch (Exception e){
            e.printStackTrace();
        
        }
        
      //  jRadioButton1.setText(jTable1.getValueAt(r,3).toString());
        int st=jTable1.getSelectedRow();
        jComboBox1.setSelectedItem(jTable1.getValueAt(st,3));
        jTextField2.setText(jTable1.getValueAt(r,4).toString());
        jTextArea2.setText(jTable1.getValueAt(r,5).toString());
        String s1=(jTable1.getValueAt(r, 6)).toString();
        jLabel13.setIcon(ResizeImage(s1));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        String agree_no = jTextField3.getText();
        if(agree_no.equals("")|| agree_no.equals(null)){
            JOptionPane.showMessageDialog(null, "Please enter the Agreement no","Error in agree_no", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getConnection().createStatement();
               st.executeUpdate("DELETE from sub_contractor_agreement where Id_sub='"+agree_no+"'");
               
               jTextField3.setText(null);
            jTextArea1.setText(null);
            jDateChooser1.setDate(null);
            jComboBox1.setSelectedItem(0);
            jTextField2.setText(null);
            jTextArea2.setText(null);
            jLabel13.setIcon(null);
            jLabel13.setText(null);
               
           } catch (Exception e) {
               e.printStackTrace();
           }
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
         tableload();
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed

         char c = evt.getKeyChar();
    if ((Character.isDigit(c))) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only Digit");
    }
     
    
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        
        
    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
         String agree_no=jTextField3.getText();
         String descr=jTextArea1.getText();
         
         Date signdate=jDateChooser1.getDate();
         SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
         String date= sdm.format(signdate);
         
//         String sign = null;
//            if(jRadioButton1.isSelected()){
//                sign="yes";
//            }else if(jRadioButton2.isSelected()){
//                sign="no";
//            }
         String sign_by=jComboBox1.getSelectedItem().toString();
         String est_sett=jTextField2.getText();
         String add_want=jTextArea2.getText();
         String image=jLabel13.getText();
         
          image = image.replace("\\","/");
         
         if (agree_no.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Agreement No");
          
          else if (descr.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Descriptions");
          
          else if (est_sett.isEmpty()) 
                     JOptionPane.showMessageDialog(null,"Enter the Estimate Settlement");
         
          else{ 
                try {
             Statement st= db.getConnection().createStatement();
             st.executeUpdate("update sub_contractor_agreement set Id_sub='"+agree_no+"',descrp='"+descr+"',Contract_date='"+date+"',signby='"+sign_by+"',Est_settelment='"+est_sett+"',addit_want='"+add_want+"',image='"+image+"' where Id_sub='"+agree_no+"'");
             JOptionPane.showMessageDialog(null,"Successfully Update...!");
             
             jTextField3.setText(null);
            jTextArea1.setText(null);
            jDateChooser1.setDate(null);
            jComboBox1.setSelectedIndex(0);
            jTextField2.setText(null);
            jTextArea2.setText(null);
            jLabel13.setIcon(null);
            jLabel13.setText(null);
            
            
             
             DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
         tableload();
        } catch (Exception e) {
            e.printStackTrace();
        }
                
     }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jDateChooser1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseReleased
        
    }//GEN-LAST:event_jDateChooser1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {
            Connection c= Software_Jframes.db.statement().getConnection();
        
            //String report = "";
            JasperDesign jd = JRXmlLoader.load("C:\\Users\\Asbar Ali\\Documents\\Building_Constructions\\src\\Ireports\\subcon_agree.jrxml");
            String sql = "SELECT\n" +
"     sub_contractor_agreement.`Id_sub` AS sub_contractor_agreement_Id_sub,\n" +
"     sub_contractor_agreement.`Est_settelment` AS sub_contractor_agreement_Est_settelment,\n" +
"     sub_contractor_agreement.`Contract_date` AS sub_contractor_agreement_Contract_date,\n" +
"     sub_contractor_agreement.`descrp` AS sub_contractor_agreement_descrp,\n" +
"     sub_contractor_agreement.`Sub_cont_id` AS sub_contractor_agreement_Sub_cont_id,\n" +
"     sub_contractor_agreement.`conatract_sighn` AS sub_contractor_agreement_conatract_sighn,\n" +
"     sub_contractor_agreement.`addit_want` AS sub_contractor_agreement_addit_want,\n" +
"     sub_contractor_agreement.`image` AS sub_contractor_agreement_image,\n" +
"     sub_contractor_agreement.`signby` AS sub_contractor_agreement_signby\n" +
"FROM\n" +
"     `sub_contractor_agreement` sub_contractor_agreement";
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp =JasperFillManager.fillReport(jr,null,c);
            JasperViewer.viewReport(jp);
            JasperViewer.viewReport(jp, isClosed);
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jButton4ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
    
    public void tableload( ){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         try {
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from sub_contractor_agreement");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("Id_sub"));
            v.add(rs.getString("descrp"));
            v.add(rs.getString("Contract_date"));
            //v.add(rs.getString("conatract_sighn"));
            v.add(rs.getString("signby"));
            v.add(rs.getString("Est_settelment"));
            v.add(rs.getString("addit_want"));
            v.add(rs.getString("image"));
           
            
             dtm.addRow(v);
      
           }
    }
         catch(Exception e){
         e.printStackTrace();
         
         }
    }
    public void tableload_search(String agree_no)
    {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from sub_contractor_agreement where Id_sub Like'%"+agree_no+"%'");
              while(rs.next()){  
                Vector v = new Vector();
                v.add(rs.getString("Id_sub"));
            v.add(rs.getString("descrp"));
            v.add(rs.getString("Contract_date"));
           // v.add(rs.getString("conatract_sighn"));
            v.add(rs.getString("signby"));
            v.add(rs.getString("Est_settelment"));
            v.add(rs.getString("addit_want"));
            v.add(rs.getString("image"));
            
            dtm.addRow(v);

              
              }
        
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    private boolean duplicatesAgreeno() {
        String agr_no = jTextField3.getText();
        int i=0;
        try {
            
            ResultSet rs= db.getConnection().createStatement().executeQuery("select Id_sub from sub_contractor_agreement");
            while (rs.next()){
            String ag_no =  rs.getString("Id_sub");
            if(ag_no.equals(agr_no)){
                i=i+1;
            }
            }
            
           
        } catch (Exception e) {
        }
         if(i==1){
             JOptionPane.showMessageDialog(null,"You have already Added this Agreement No only you can Update Now");
             return true;
            }else{
             return false;
         }
    } 
      private void sign_combo(){
        try {
           Statement st= db.getConnection().createStatement();
           ResultSet rs=st.executeQuery("select * from employee");
           
           while(rs.next())
           {
               jComboBox1.addItem(rs.getString(4));          
           }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
  
//   public void valid_date(){
// 
//    String  rdate=jLabel5.getText();
////        SimpleDateFormat sdm = new SimpleDateFormat("yyyy");
////        String rdateY= sdm.format(rdate);
////        SimpleDateFormat sdm1 = new SimpleDateFormat("MM");
////        String rdateM= sdm1.format(rdate);
////        SimpleDateFormat sdm2 = new SimpleDateFormat("dd");
////        String rdateD= sdm2.format(rdate);
////        System.out.println(rdateY+" "+rdateM+" "+rdateD);
//        //----------------------------//
//        Date  ddate=jDateChooser1.getDate();
//        SimpleDateFormat sdm3 = new SimpleDateFormat("yyyy");
//        String ddateY= sdm3.format(ddate);
//        SimpleDateFormat sdm4 = new SimpleDateFormat("MM");
//        String ddateM= sdm4.format(ddate);
//        SimpleDateFormat sdm5 = new SimpleDateFormat("dd");
//        String ddateD= sdm5.format(ddate);
//        System.out.println(ddateY+" -  "+ddateM+" -  "+ddateD);
////        int rdateYY=Integer.parseInt(rdateY);
////        int rdateMM=Integer.parseInt(rdateM);
////        int rdateDD=Integer.parseInt(rdateD);
//          int ddateYY=Integer.parseInt(ddateY);
//          int ddateMM=Integer.parseInt(ddateM);
//          int ddateDD=Integer.parseInt(ddateD);
//                  
//                  
//        if( (ddateYY <= rdateYY) && (ddateMM <= rdateMM) && (ddateDD < rdateDD) ){
//            JOptionPane.showMessageDialog(null, "Invalid Date");
//        }
//        else{
//            
//         }
    
}


    

