/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package subcontractor;

import test_new.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author westlifzzz
 */
public class task_alloction extends javax.swing.JInternalFrame {

    /**
     * Creates new form task_alloction
     */
    public task_alloction() {
        initComponents();
        loadcombospecialization();
        check_sub_due();
  //      taskcombo();
        pay_methodcombo();
        // DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        // dtm.setRowCount(0);
         tableload_taskAllocaton();
        
        random();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox6 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1340, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Task Allocation");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 250, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Search Avaliable Subcontractor");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 510, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Select Site");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -50, 1180, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 770, 30));

        jLabel8.setText("Special Field");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Sub_ID", "Special_Field"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 490, 110));

        jLabel12.setText("Project ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 70, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Allocate task");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1340, 40));

        jLabel2.setText("Allocate task");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, 23));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Allocate task", "Allocate type", "Start Date", "Due Date", "No labours", "Payment type", "Poject ID"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 630, 140));

        jLabel3.setText("Start Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 61, 22));

        jLabel4.setText("Due Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 60, -1));

        jLabel5.setText("Payment Method");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 100, 20));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 200, -1));

        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 140, 30));

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 140, 30));

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 140, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 200, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 200, -1));

        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 200, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("with materials");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("without materials");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel6.setText("Selected subcontrator ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 20));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 130, 20));

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 140, 30));

        jLabel18.setText("No of labours");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 80, -1));

        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField8MouseEntered(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 200, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pro ID", "Project Name", "Address"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 550, 90));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 200, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, 140, 30));

        jLabel1.setText("Task ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 50, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 140, 20));

        jLabel10.setText("Project ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 80, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 130, 20));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 354, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
        String task_id = jLabel7.getText();
        if(task_id.equals("")|| task_id.equals(null)){
            JOptionPane.showMessageDialog(null, "Please enter the Task ID","Error in Task ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getConnection().createStatement();
               st.executeUpdate("DELETE from task_allocate where task_id='"+task_id+"'");
               
               jLabel7.setText("");    
        jLabel15.setText("");
        jRadioButton1.setSelected(true);
        jTextField8.setText("");
        jDateChooser1.setCalendar(null);
        jDateChooser2.setCalendar(null);
        jComboBox2.setSelectedItem("");
        jLabel17.setText("");
        jLabel14.setText("");
        
        random();
               
               
           } catch (Exception e) {
               e.printStackTrace();
           }
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         String task_id=jLabel7.getText();
         String all_task=jLabel15.getText();
         
         String all_type=null;
         if(jRadioButton1.isSelected())
         {
             all_type="with materials";
         }
         else{
             all_type="without materials";
         }
         
         Date Date_of_add=jDateChooser1.getDate();
         SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
         String start_date= sdm.format(Date_of_add);
         
         Date Date_of_add1=jDateChooser2.getDate();
         SimpleDateFormat sdm1 = new SimpleDateFormat("yyyy-MM-dd");
         String due_date= sdm1.format(Date_of_add1);
         
         String no_labur=jTextField8.getText();
         String pay_method=jComboBox2.getSelectedItem().toString();
         
         try {
             Statement st= db.getConnection().createStatement();
             st.executeUpdate("update task_allocate set Allocated_task='"+all_task+"',Allocation_type='"+all_type+"',Start_date='"+start_date+"',Due_date='"+due_date+"',no_labours='"+no_labur+"',Payment_method='"+pay_method+"' where task_id='"+task_id+"'");
             
             jLabel7.setText("");    
        jLabel15.setText("");
        jRadioButton1.setSelected(true);
        jTextField8.setText("");
        jDateChooser1.setCalendar(null);
        jDateChooser2.setCalendar(null);
        jComboBox2.setSelectedItem("");
        jLabel17.setText("");
        jLabel14.setText("");
        
        random();
             
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String task_id=jLabel7.getText();
        String all_task = jLabel15.getText();
        
        String all_type = null;
            if(jRadioButton1.isSelected()){
                all_type="with materials";
            }else{
                all_type="without materials";
            }
            
         
        Date str_date = jDateChooser1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateString =sdf.format(str_date);
        
        Date due_date = jDateChooser2.getDate();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String dateString1 = sdf1.format(due_date);
        
        String no_laburs=jTextField8.getText();
        String pay_method=jComboBox2.getSelectedItem().toString();
        String sub_id=jLabel17.getText();
        String pro_id=jLabel14.getText();
        try {
      
            
            Statement st= db.getConnection().createStatement();
            st.executeUpdate("Insert into task_allocate (task_id,Allocated_task, Allocation_type, Start_date, Due_date, Payment_method,no_labours,sub_id,pro_id) values('"+task_id+"','"+all_task+"','"+all_type+"','"+dateString+"','"+dateString1+"','"+pay_method+"','"+no_laburs+"','"+sub_id+"','"+pro_id+"')");
            JOptionPane.showMessageDialog(null,"Successfully Saved...!");
            
        jLabel7.setText("");    
        jLabel15.setText("");
        jRadioButton1.setSelected(true);
        jTextField8.setText("");
        jDateChooser1.setCalendar(null);
        jDateChooser2.setCalendar(null);
        jComboBox2.setSelectedItem("");
        jLabel17.setText("");
        jLabel14.setText("");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
         DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         dtm.setRowCount(0);
         tableload_taskAllocaton();
        
        random();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
    
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        String spc= jComboBox6.getSelectedItem().toString();
        
        try {
          
          
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from"
                   + " subcontrator_special_field,sub_contract_register,task_allocate where subid=Sub_contr_reg and fields='"+spc+"'");
           while(rs.next()){
               
               Vector v = new Vector();
              
               v.add(rs.getString("First_name"));
               v.add(rs.getString("Sub_contr_reg"));
               v.add(rs.getString("fields"));
               dtm.addRow(v);
               
           }
          
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
      
      int i=jTable1.getSelectedRow();
      
      jLabel17.setText(dtm.getValueAt(i, 1)+"");
      jLabel15.setText(dtm.getValueAt(i, 2)+"");
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String pro_id=jTextField1.getText();
        if(pro_id.equals("") || pro_id.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Projec ID ","Error in Project ID",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
            dtm.setRowCount(0);
            
           tableload_project(pro_id); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       
        int r =jTable2.getSelectedRow();
        
        jLabel7.setText(jTable2.getValueAt(r,0).toString());
        jLabel15.setText(jTable2.getValueAt(r,1).toString());
   //     jComboBox4.setSelectedItem(jTable1.getValueAt(r,1).toString());
//        String all_type = null;
//            if(jRadioButton1.isSelected()){
//                all_type="with materials";
//                jRadioButton1.setText(jTable2.getValueAt(r,2).toString());
//            }else{
//                all_type="without materials";
//            }
           
          jRadioButton1.setText(jTable2.getValueAt(r,2).toString());  
        
        
        
        
        
        String start_date=jTable2.getValueAt(r,3 ).toString();
        try{
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date1=format.parse(start_date);
            jDateChooser1.setDate(date1);
        }catch (Exception e){
            e.printStackTrace();
        
        }
        String due_date=jTable2.getValueAt(r,4 ).toString();
        try{
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date2=format.parse(due_date);
            jDateChooser2.setDate(date2);
        }catch (Exception e){
            e.printStackTrace();
        
        }
       
        jTextField8.setText(jTable2.getValueAt(r,5).toString());
        jComboBox2.setSelectedItem(jTable2.getValueAt(r,6).toString());
        jLabel14.setText(jTable2.getValueAt(r,7).toString());
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        char c = evt.getKeyChar();
    if ((Character.isDigit(c))) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only Digit");
    }//GEN-LAST:event_jTextField8KeyReleased
    }
    private void jTextField8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseEntered
         
        Date  rdate=jDateChooser1.getDate();
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy");
        String rdateY= sdm.format(rdate);
        SimpleDateFormat sdm1 = new SimpleDateFormat("MM");
        String rdateM= sdm1.format(rdate);
        SimpleDateFormat sdm2 = new SimpleDateFormat("dd");
        String rdateD= sdm2.format(rdate);
        System.out.println(rdateY+" "+rdateM+" "+rdateD);
        //----------------------------//
        Date  ddate=jDateChooser2.getDate();
        SimpleDateFormat sdm3 = new SimpleDateFormat("yyyy");
        String ddateY= sdm3.format(ddate);
        SimpleDateFormat sdm4 = new SimpleDateFormat("MM");
        String ddateM= sdm4.format(ddate);
        SimpleDateFormat sdm5 = new SimpleDateFormat("dd");
        String ddateD= sdm5.format(ddate);
        System.out.println(ddateY+" -  "+ddateM+" -  "+ddateD);
        int rdateYY=Integer.parseInt(rdateY);
        int rdateMM=Integer.parseInt(rdateM);
        int rdateDD=Integer.parseInt(rdateD);
          int ddateYY=Integer.parseInt(ddateY);
          int ddateMM=Integer.parseInt(ddateM);
          int ddateDD=Integer.parseInt(ddateD);
                  
                  
        if( (ddateYY <= rdateYY) && (ddateMM <= rdateMM) && (ddateDD < rdateDD) ){
            JOptionPane.showMessageDialog(null, "Invalid Date");
        }
        else{
            
         }
    }//GEN-LAST:event_jTextField8MouseEntered
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    public void tableload_taskAllocaton(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         try {
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from task_allocate");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("task_id"));
            v.add(rs.getString("Allocated_task"));
            v.add(rs.getString("Allocation_type"));
            v.add(rs.getString("Start_date"));
            v.add(rs.getString("Due_date"));
            v.add(rs.getString("no_labours"));
            v.add(rs.getString("Payment_method"));
            v.add(rs.getString("pro_id"));
            
             dtm.addRow(v);
      
           }
    }
         catch(Exception e){
         e.printStackTrace();
         
         }
    }
    
    public void  tableload_project(String pro_id){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
         try {
           ResultSet rs= db.getConnection().createStatement().executeQuery("select * from con_sites where id Like'%"+pro_id+"%'");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("id"));
            v.add(rs.getString("name"));
            v.add(rs.getString("location"));
            
            jLabel14.setText(rs.getString("id"));
             dtm.addRow(v);
      
           }
    }
         catch(Exception e){
         e.printStackTrace();
         
         }
        
    }
    private void loadcombospecialization() {
        
        try {
            ResultSet rs= db.getConnection().createStatement().executeQuery("select Options from specilizat_sub_cont ");
            jComboBox6.removeAllItems();
            while(rs.next()){
                
               jComboBox6.addItem(rs.getString("Options"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
//    private void taskcombo(){
//         try {
//           Statement st= db.getConnection().createStatement();
//           ResultSet rs=st.executeQuery("select * from specilizat_sub_cont");
//           
//           while(rs.next())
//           {
//            //   jComboBox4.addItem(rs.getString(3));          
//           }
//           
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    
    private void pay_methodcombo(){
        try {
           Statement st= db.getConnection().createStatement();
           ResultSet rs=st.executeQuery("select * from sub_payment");
           
           while(rs.next())
           {
               jComboBox2.addItem(rs.getString(5));          
           }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
            

    private void check_sub_due() {
        try {
             ResultSet rs1 = db.getConnection().createStatement().executeQuery("select * from task_allocate");
           while(rs1.next()){
               String str = rs1.getString("Due_date");
               DateFormat format= new SimpleDateFormat("yyyy-MM-dd");
               Date d = format.parse(str);
               
                Calendar cal = Calendar.getInstance();
                cal.setTime(d);
                String formatedDate = cal.get(Calendar.YEAR) + "-" + (cal.get(Calendar.MONTH) + 1) + "-" + cal.get(Calendar.DATE);
                 int year1 = cal.get(Calendar.YEAR);
                 int mon1=cal.get(Calendar.MONTH);
                 int date1 = cal.get(Calendar.DATE);
                
             //   System.out.println("formatedDate : " + formatedDate); 
                
                Date d1 = new Date();
                Calendar cal1 = Calendar.getInstance();
                cal.setTime(d1);
                String formatedDate1 = cal.get(Calendar.YEAR) + "-" + (cal.get(Calendar.MONTH) + 1) + "-" + cal.get(Calendar.DATE);
             //   System.out.println("formatedDate : " + formatedDate); 
                
                int year2 = cal1.get(Calendar.YEAR);
                int mon2=cal1.get(Calendar.MONTH);
                int date2 = cal1.get(Calendar.DATE);
                
           //     System.out.println(year1);
           //     System.out.println(mon1);
           //     System.out.println(date1);
                
           //     System.out.println(year2);
           //     System.out.println(mon2);
           //     System.out.println(date2);
                
                if(year2> year1){
                          try {
                        db.getConnection().createStatement().executeUpdate("update sub_contract_register set allocate='no' where Sub_contr_reg='"+rs1.getInt("sub_id")+"' ");
                          
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }else if(mon2>mon1){
               
                     try {
                        db.getConnection().createStatement().executeUpdate("update sub_contract_register set allocate='no' where Sub_contr_reg='"+rs1.getInt("sub_id")+"' ");
                          
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }else if(date2 > date1){
                     
                     try {
                        db.getConnection().createStatement().executeUpdate("update sub_contract_register set allocate='no' where Sub_contr_reg='"+rs1.getInt("sub_id")+"' ");
                          
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                
                           }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void random()
    {
        Random r = new Random();
        int n= r.nextInt(520)+7;
        jLabel7.setText(n+"");
    }
}
