/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HR;

import test_new.*;
import java.awt.Image;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandakelum
 */
public class attendant extends javax.swing.JInternalFrame {

    /**
     * Creates new form attendant
     */
    public attendant() {
        initComponents();
        jRadioButton5.setSelected(true);
        jRadioButton1.setSelected(true);
        leavestatusalready_added();
        alreadyadd();
        searchAttendence();
        searchleave_status();
       
        Date dd = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String d= sdf.format(dd);
        String part[] = d.split("-");
        int da = Integer.parseInt(part[1]);
       
        jLabel5.setText(d+"");
        jLabel6.setText(d+"");
        jLabel7.setText(da+"");
    }
     
 public ImageIcon ResizeImage(String ImagePath) { 
        ImageIcon MyImage = new ImageIcon(ImagePath); Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel16.getWidth(), jLabel16.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg); 
        return image;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jTextField39 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTimeChooser3 = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jTimeChooser2 = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Employee Id");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 140, 140));

        jLabel20.setText("Current Taken Day Offs      ");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 160, -1));

        jLabel54.setText("Half Day");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 100, 20));

        jLabel61.setText("Status");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, 20));
        jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 102, -1));

        jLabel63.setText("Time in");
        jPanel5.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 50, 20));

        jLabel64.setText("Time Out");
        jPanel5.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 60, 20));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 51, 51));
        jLabel48.setText("Mark Aattendence of Employees");
        jPanel11.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setText("Leave Type");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 68, 25));

        jLabel52.setText("Payment Type");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 100, 27));

        jLabel55.setText("Medical");
        jPanel13.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 69, 27));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("No");
        jPanel13.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Yes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel13.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 90, -1));
        jPanel13.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 132, -1));

        jLabel57.setText("Reason");
        jPanel13.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 58, 27));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Payment", "Half Payment" }));
        jPanel13.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 140, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full Day", "Half Day" }));
        jPanel13.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 130, -1));
        jPanel13.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 140, -1));

        jLabel2.setText("Date");
        jPanel13.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 60, 20));

        jLabel17.setText("Employee Id");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, -1));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 1110, 220));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 51, 51));
        jLabel58.setText("Request Leaves");
        jPanel15.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Click Here to See Leave History");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 240, 190, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Absent", "Present" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("No");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Yes");
        jPanel5.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 51, 51));
        jLabel70.setText("Month");
        jPanel19.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 51, 51));
        jLabel75.setText("Attendence Status Of (Date)");
        jPanel20.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 51, 51));
        jLabel76.setText("Attendence Status Of (Date)");
        jPanel21.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 51, 51));
        jLabel77.setText("Attendence Status Of (Date)");
        jPanel22.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jLabel7.setText("jLabel7");
        jPanel19.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 20, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 51, 51));
        jLabel71.setText("Leave Status Of  ");
        jPanel19.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel5.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 430, 30));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 51, 51));
        jLabel78.setText("Attendence Status Of  ");
        jPanel23.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 51, 51));
        jLabel79.setText("Attendence Status Of (Date)");
        jPanel24.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 51, 51));
        jLabel80.setText("Attendence Status Of (Date)");
        jPanel25.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 51, 51));
        jLabel81.setText("Attendence Status Of (Date)");
        jPanel26.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jPanel23.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 30));

        jLabel6.setText("jLabel6");
        jPanel23.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel5.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 430, 30));

        jLabel83.setText("Current taken short leaves");
        jPanel5.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 150, 20));
        jPanel5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 102, -1));

        jButton18.setText("Overview of  Leaves");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 270, 160, -1));

        jLabel84.setText("OT Hours");
        jPanel5.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, 20));

        jLabel1.setText("Date");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 70, -1));

        jLabel4.setText("0");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 70, 20));
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 110, 10));

        jLabel18.setText("Employee Id");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 100, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 100, -1));

        jLabel9.setText("Employee ID");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 90, -1));

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));
        jPanel5.add(jTimeChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, -1));
        jPanel5.add(jTimeChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, -1));

        jLabel10.setText("Employee ID");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, -1));

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 90, 80, -1));

        jButton21.setText("Add");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton16.setText("Update");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21)
                    .addComponent(jButton16)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 560, 350));

        jButton20.setText("Update");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton19.setText("Add");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jButton19)
                .addGap(18, 18, 18)
                .addComponent(jButton20)
                .addGap(35, 35, 35))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 460, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        String aid= jTextField3.getText();
          if(noemployee()){
            return;
        }
          else if(updateattendence())
        {
            return;
        }
        String time_i= jTimeChooser3.getFormatedTime();
        String time_o= jTimeChooser2.getFormatedTime();
        
        String date = jLabel5.getText();
        
        
        String parts[] = time_i.split(":");
        String part[] = time_o.split(":");

        int a = Integer.parseInt(parts[0]);
        int b = Integer.parseInt(part[0]);
        int c = b-a;
        c=c-4;
        if(c<0){
            JOptionPane.showMessageDialog(null,"Please enter a valid time","Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jLabel4.setText(c+"");
        String thours=   jLabel4.getText();

        String status= jComboBox2.getSelectedItem().toString();

        String S_Leaves=null;

        if(jRadioButton6.isSelected()){
            S_Leaves="yes";
        }else{
            S_Leaves="No";
        }

        String dat_emp=aid+date;
        try {
            db.connect().createStatement().executeUpdate("update attendence set time_in='"+time_i+"', time_out='"+time_o+"', "
                + "THours='"+thours+"', status='"+status+"',short_l='"+S_Leaves+"', date='"+date+"' where emp_date='"+dat_emp+"' ");

            JOptionPane.showMessageDialog(null, "Successfully Updated","Message",JOptionPane.INFORMATION_MESSAGE);
            
            jTextField3.setText(null);
            jTextField4.setText(null);
            jLabel4.setText("0");
            jLabel5.setText(null);
            jRadioButton5.setSelected(true);
            Date dd = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String d= sdf.format(dd);
            jLabel5.setText(d+"");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        String aid= jTextField3.getText();
        if(noemployee()){
            return;
        }
        else if(alreadyadd()){
            return;
        }
        String time_i= jTimeChooser3.getFormatedTime();
        String time_o= jTimeChooser2.getFormatedTime();
        
        String date = jLabel5.getText();
        
        
        String parts[] = time_i.split(":");
        String part[] = time_o.split(":");

        int a = Integer.parseInt(parts[0]);
        int b = Integer.parseInt(part[0]);
        int c = b-a;
        int ot=b-a;
        c=c-4;
        
        if(c != -4){
        if(c<0){
            JOptionPane.showMessageDialog(null,"Please enter a valid time","Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        }
        ot=ot-8;
        if(ot>0){
           jLabel4.setText(ot+"");
        }else{
            jLabel4.setText(0+"");
        }
        
        String thours=   jLabel4.getText();

        String status= jComboBox2.getSelectedItem().toString();

        String S_Leaves=null;

        if(jRadioButton6.isSelected()){
            S_Leaves="yes";
        }else{
            S_Leaves="No";
        }

        String dat_emp=aid+date;

        try {
            db.connect().createStatement().executeUpdate("insert into attendence (eid, time_in, time_out, short_l, THours, status, date, emp_date)"
                + " values ('"+aid+"','"+time_i+"','"+time_o+"','"+S_Leaves+"','"+thours+"','"+status+"','"+date+"','"+dat_emp+"') ");

            JOptionPane.showMessageDialog(null, "Successfully Saved","Message",JOptionPane.INFORMATION_MESSAGE);

            jTextField3.setText(null);
            jTextField4.setText(null);
            jLabel4.setText("0");
            jLabel5.setText(null);
            jRadioButton5.setSelected(true);
            Date dd = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String d= sdf.format(dd);
            jLabel5.setText(d+"");
            
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add yo
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Leave l = new Leave();
        l.setVisible(true);
       
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
          String rid= jTextField5.getText();
          if(noemp_l_req()){
              return;
          }
        String reas= jTextField39.getText();
        String medical=null;
        String leave_t= jComboBox3.getSelectedItem().toString();
        String payment_t= jComboBox1.getSelectedItem().toString();
        if(jRadioButton2.isSelected()){
            medical="yes";
        }else{
            medical="No";
        }
        Date dateFromDateChooser = jDateChooser2.getDate();
        String dateString = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser);
       
        try {
            db.connect().createStatement().executeUpdate("insert into leave_request (idemployee, reason, l_type, Medical, payment_type, date)"
                + " values ('"+rid+"','"+reas+"','"+leave_t+"','"+medical+"','"+payment_t+"','"+dateString+"') ");

            JOptionPane.showMessageDialog(null, "Successfully Saved","Message",JOptionPane.INFORMATION_MESSAGE);

            jTextField39.setText("");
            jRadioButton1.setSelected(true);
            jTextField5.setText("");
            jDateChooser2.setCalendar(null);
//            requestcombo();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
       searchleave_status();
       iamgeload_leavestatus();
       noemp_leave();
      
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         searchleave_status();
         iamgeload_leavestatus();
         noemp_leave();
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        searchAttendence();
        imageload_atte();
        noemployee();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
      
        searchAttendence();
        imageload_atte();
         noemployee();
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String aid= jTextField1.getText();
        if(noemp_leave()){
            return;
        }
        String ctl= jTextField21.getText();

        String ctsl= jTextField29.getText();

        try {
            db.connect().createStatement().executeUpdate("delete from leave_status where Emp_id='"+aid+"'");
            JOptionPane.showMessageDialog(null,"Successfully deleted","Deleted Message",JOptionPane.ERROR_MESSAGE);

            jTextField2.setText("");
            jTextField1.setText("");
            jTextField21.setText("");
            jTextField29.setText("");

        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String aid= jTextField1.getText();
        if(noemp_leave()){
            return;
        }
        else  if(updateLeave_s()){
            return;
        }
        String ctl= jTextField21.getText();

        String ctsl= jTextField29.getText();

        if ( !ctl.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null,"Current Taken Day Off's should be Digits");
            jTextField21.setText("");
        }
        else  if ( !ctsl.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null,"Current Taken Short Leaves should be Digits");
            jTextField29.setText("");
        }

        try {
            db.connect().createStatement().executeUpdate("update leave_status set current_l='"+ctl+"', current_sh_l='"+ctsl+"' where Emp_Id='"+aid+"' ");

            JOptionPane.showMessageDialog(null, "Successfully Updated","Message",JOptionPane.INFORMATION_MESSAGE);

            jTextField2.setText("");
            jTextField1.setText("");
            jTextField21.setText("");
            jTextField29.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        String aid= jTextField1.getText();
        if(noemp_leave()){
            return;
        }
        else  if(leavestatusalready_added()){
            return;
        }
        String ctl= jTextField21.getText();

        String ctsl= jTextField29.getText();

        if ( !ctl.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null,"Current Taken Day Off's should be Digits");
            jTextField21.setText("");
        }
        else  if ( !ctsl.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null,"Current Taken Short Leaves should be Digits");
            jTextField29.setText("");
        }else{

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String da = sdf.format(d);

            String date[] = da.split("-");

            String mnth_emp=aid+date[0]+date[1];

            try {
                db.connect().createStatement().executeUpdate("insert into leave_status (Emp_Id, current_l, current_sh_l, emp_mnth)"
                    + " values ('"+aid+"','"+ctl+"','"+ctsl+"','"+mnth_emp+"') ");

                JOptionPane.showMessageDialog(null, "Successfully Added","Message",JOptionPane.INFORMATION_MESSAGE);

                jTextField2.setText("");
                jTextField1.setText("");
                jTextField21.setText("");
                jTextField29.setText("");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeChooser2;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeChooser3;
    // End of variables declaration//GEN-END:variables


    private void searchleave_status() {
        String id= jTextField2.getText();
            
            try {
                ResultSet rs=   db.connect().createStatement().executeQuery("select * from leave_status where Emp_id='"+id+"'");
     
                while(rs.next()){
                   jTextField1.setText(rs.getString("Emp_id"));
                   jTextField21.setText(rs.getInt("current_l")+"");
                   jTextField29.setText(rs.getInt("current_sh_l")+"");
               
                }
            
            } catch (Exception e) {
        }
    }

    private boolean leavestatusalready_added() {
       String id1 = jTextField2.getText();
        int i=0;
       Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String da = sdf.format(d);
        
        String date[] = da.split("-");
        
         String id=id1+date[0]+date[1];
        try {
           
            ResultSet rs= db.connect().createStatement().executeQuery("select emp_mnth from leave_status");
            while (rs.next()){
            String idem =  rs.getString("emp_mnth");
            if(idem.equals(id)){
                i=i+1;
            }
            }
        } catch (Exception e) {
        }
        if(i==1){
             JOptionPane.showMessageDialog(null,"You have already Added this Employee only you can update now");
             return true;
            }else{
            return false;
        }
    }

    private void searchAttendence() {
        String id= jTextField4.getText();
        String date = jLabel5.getText();
        String dat_em=id+date;  
         
         
            try {
                ResultSet rs=   db.connect().createStatement().executeQuery("select * from attendence where emp_date='"+dat_em+"'");
                while(rs.next()){
                   jTextField3.setText(rs.getString("eid"));
                   String sta = rs.getString("status");
                   
                   if(sta.equals("Present")){
                       jComboBox1.addItem("Present");
                       jComboBox1.addItem("Absent");
                       
                    }else{
                       jComboBox1.addItem("Absent");
                       jComboBox1.addItem("Present");
                   }
                   
                   String sl = rs.getString("short_l");
                   if(sl.equals("yes")){
                       jRadioButton6.setSelected(true);
                       
                    }else if(sl.equals("No")){
                       jRadioButton5.setSelected(true);
                   }
                   
                   jTimeChooser3.setTime(rs.getTime("time_in"));
                    jTimeChooser2.setTime(rs.getTime("time_out"));
                   jLabel4.setText(rs.getString("THours"));
                   jLabel5.setText(rs.getString("date"));
               
                }
            
            } catch (Exception e) {
              
        }
    }

//    private void alreadyadd() {
//        
//    }

    private boolean noemployee() {
         String id2 = jTextField3.getText();
         int i=0;
        try {
            
            ResultSet rs= db.connect().createStatement().executeQuery("select idemployee from employee");
            while (rs.next()){
            String idem =  rs.getString("idemployee");
            if( idem.equals(id2)){
                i=i+1;
            } else {
            }
            }
            
          
            }
        catch (Exception e) {
        }
          if(i==0){
             JOptionPane.showMessageDialog(null,"There is no employee with this ID");
             jTextField3.setText("");
             jTextField4.setText("");
             return true;
            }else{
                return false;
            }
    }

    private boolean alreadyadd() {
        String id1 = jTextField3.getText();
        String date = jLabel5.getText();
         int i=0;
        String temp=id1+date;
        try {
           
            ResultSet rs= db.connect().createStatement().executeQuery("select emp_date from attendence");
            while (rs.next()){
            String idem =  rs.getString("emp_date");
            if(idem.equals(temp)){
                i=i+1;
            }
            }
            
            
        } catch (Exception e) {
        }
        if(i==1){
             JOptionPane.showMessageDialog(null,"You have already Addded this Employee only you can Update Now");
             return true;
            }else{
            return false;
        }
    }

    private boolean noemp_leave() {
         String id2 = jTextField1.getText();
         int i=0;
        try {
            
            ResultSet rs= db.connect().createStatement().executeQuery("select idemployee from employee");
            while (rs.next()){
            String idem =  rs.getString("idemployee");
            if( idem.equals(id2)){
                i=i+1;
            } else {
            }
            }
            
          
            }
        catch (Exception e) {
        }
          if(i==0){
             JOptionPane.showMessageDialog(null,"There is no employee Registered with this ID");
             jTextField1.setText("");
             jTextField2.setText("");
             return true;
            }else{
                return false;
            }
    }

    private boolean noemp_l_req() {
       String id2 = jTextField5.getText();
         int i=0;
        try {
            
            ResultSet rs= db.connect().createStatement().executeQuery("select idemployee from employee");
            while (rs.next()){
            String idem =  rs.getString("idemployee");
            if( idem.equals(id2)){
                i=i+1;
            } else {
            }
            }
            
          
            }
        catch (Exception e) {
        }
          if(i==0){
             JOptionPane.showMessageDialog(null,"There is no employee registered with this ID");
             jTextField5.setText("");
             return true;
            }else{
                return false;
            }
    }

    private void imageload_atte() {
        String id= jTextField4.getText();  
            try {
                ResultSet rs=   db.connect().createStatement().executeQuery("select * from employee where idemployee='"+id+"'");
     
                while(rs.next()){
                   
                   String emp = rs.getString("empimage");
                   
                 
                   
                     jLabel16.setIcon(ResizeImage(emp));
                     
                   
                   
                }
            
            } catch (Exception e) {
        }
    }

    private void iamgeload_leavestatus() {
        String id= jTextField2.getText();  
            try {
                ResultSet rs=   db.connect().createStatement().executeQuery("select * from employee where idemployee='"+id+"'");
     
                while(rs.next()){
                   
                   String emp = rs.getString("empimage");
                   
                 
                   
                     jLabel16.setIcon(ResizeImage(emp));  
                   
                }
            
            } catch (Exception e) {
        }
    }

    private boolean updateattendence() {
       String id1 = jTextField3.getText();
         int i=0;
        try {
            
            ResultSet rs= db.connect().createStatement().executeQuery("select eid from attendence");
            while (rs.next()){
            String idem =  rs.getString("eid");
            if(idem.equals(id1)){
                i=i+1;
            }
            }
            
            
        } catch (Exception e) {
        }
        if(i==0){
             JOptionPane.showMessageDialog(null,"You have Not registered This Employee");
             return true;
            }else{
            return false; 
        }
    }

    private boolean updateLeave_s() {
      String id1 = jTextField1.getText();
         int i=0;
        try {
            
            ResultSet rs= db.connect().createStatement().executeQuery("select Emp_id from leave_status");
            while (rs.next()){
            String idem =  rs.getString("Emp_id");
            if(idem.equals(id1)){
                i=i+1;
            }
            }
            
            
        } catch (Exception e) {
        }
        if(i==0){
             JOptionPane.showMessageDialog(null,"You have Not registered This Employee");
             return true;
            }else{
            return false; 
        }   
    }
    
}
