/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import test_new.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demo
 */
public class Add_meterial extends javax.swing.JInternalFrame {

    /**
     * Creates new form 
     */
    public Add_meterial() {
        initComponents();
        
        tableload();
    }
public void tableload(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from add_meterial");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("Mat_sub_cat"));
            v.add(rs.getString("material_no"));
            v.add(rs.getString("Mat_Name"));
            v.add(rs.getString("Rack_no"));
            v.add(rs.getString("Date_of_Addition"));
            v.add(rs.getString("quant"));
            v.add(rs.getString("unit_price"));
            
             dtm.addRow(v);
      
           }
         }
         catch(Exception e){
         e.printStackTrace();
         
         }
        
        }
void tableload(String mat_subcat_no){
    
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from add_meterial where Mat_sub_cat Like'%"+mat_subcat_no+"%'");
              while(rs.next()){  
                Vector v = new Vector();
                v.add(rs.getString("Mat_sub_cat"));
            v.add(rs.getString("material_no"));
            v.add(rs.getString("Mat_Name"));
            v.add(rs.getString("Rack_no"));
            v.add(rs.getString("Date_of_Addition"));
            v.add(rs.getString("quant"));
            v.add(rs.getString("unit_price"));
            
            dtm.addRow(v);

              
              }
        
        }catch(Exception e){
            e.printStackTrace();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Add New Materials");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(865, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1330, -1));

        jLabel3.setText("Material Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 115, -1, -1));

        jLabel4.setText("Material No :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setText("Mat Sub Cat No :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setText("Rack No :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel7.setText("Date Of Added :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel8.setText("Quantity :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel9.setText("Unit price :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 112, 200, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 192, 200, -1));

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 232, 200, -1));

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 200, -1));

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 200, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("View Add Materials");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(749, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1330, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 120, 30));

        jLabel2.setText("Mat Sub Cat No :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mat Sub Cat No:", "Mat No", "Material Name ", "Rack No", "Date  of Addition", "Quantity", "unit_price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1310, 160));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 120, 30));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 120, 30));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 120, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 272, 200, -1));

        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, 120, 30));

        jToggleButton1.setText("Print PDF Report");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "910", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 592));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if( (jTextField3.getText().isEmpty()) ||(jTextField5.getText().isEmpty()) ||(jTextField6.getText().isEmpty()) ||(jTextField8.getText().isEmpty()) ||(jTextField9.getText().isEmpty())|| (jDateChooser1.getDateFormatString().isEmpty())){
        
         JOptionPane.showMessageDialog(null, "enter the correct values in textfield","Error in Text field",JOptionPane.ERROR_MESSAGE); 
        
        }
        
        else{
        
         String mat_name=jTextField3.getText();
         String mat_no=jComboBox1.getSelectedItem().toString();
         String mat_subcat_no=jTextField5.getText();
         String rack_no=jTextField6.getText();
         String qty=jTextField8.getText();
         String unit_price=jTextField9.getText();
         Date Date_of_add=jDateChooser1.getDate();
         
         SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
         String date= sdm.format(Date_of_add);
         
         
         
        try {
            Statement st= db.getconnection().createStatement();
            st.executeUpdate("Insert into add_meterial(Mat_sub_cat,material_no,Mat_Name,Rack_no,Date_of_Addition,quant,unit_price) values('"+mat_subcat_no +"','"+mat_no +"','"+ mat_name+"','"+rack_no+"','"+date+"','"+qty+"','"+unit_price+"')");
            JOptionPane.showMessageDialog(null,"Successfully Saved,,,");
            
            jTextField3.setText(null);
            jComboBox1.setSelectedItem(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
            jDateChooser1.setDateFormatString(null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
        tableload();
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String mat_subcat_no=jTextField1.getText();
        if(mat_subcat_no.equals("") || mat_subcat_no.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Mat_sub_cat_no","Error in Sub_cat_no",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
           tableload(mat_subcat_no); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        String mat_subcat_no = jTextField5.getText();
        if(mat_subcat_no.equals("")|| mat_subcat_no.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the relevant row","Error selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getconnection().createStatement();
               st.executeUpdate("DELETE from add_meterial where Mat_sub_cat='"+mat_subcat_no+"'");
               JOptionPane.showMessageDialog(null,"Successfully Deleted,,,");
           } catch (Exception e) {
               e.printStackTrace();
           }
       
       }
       DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
       dtm.setRowCount(0);
       tableload();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
         String mat_name=jTextField3.getText();
         String mat_no=jComboBox1.getSelectedItem().toString();
         String mat_subcat_no=jTextField5.getText();
         String rack_no=jTextField6.getText();
         String qty=jTextField8.getText();
         String unit_price=jTextField9.getText();
         Date Date_of_add=jDateChooser1.getDate();
         
         SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
         String date= sdm.format(Date_of_add);
         
         
         try {
             Statement st= db.getconnection().createStatement();
            st.executeUpdate("update add_meterial set material_no='"+mat_no+"',Mat_Name='"+mat_name+"',Rack_no='"+rack_no+"',Date_of_Addition='"+date+"',quant='"+qty+"',unit_price='"+unit_price+"' where Mat_sub_cat='"+mat_subcat_no+"'");
              JOptionPane.showMessageDialog(null,"Successfully update,,,"); 
             
        } catch (Exception e) {
            e.printStackTrace();
        }
         
          DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
          dtm.setRowCount(0);
          tableload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int r=jTable1.getSelectedRow();
        
         String mat_subcat_no=jTable1.getValueAt(r, 0).toString();
         String mat_no=jTable1.getValueAt(r, 1).toString();
         String mat_name=jTable1.getValueAt(r, 2).toString();
         String rack_no=jTable1.getValueAt(r, 3).toString();
         String date=jTable1.getValueAt(r, 4).toString();
         String qty=jTable1.getValueAt(r, 5).toString();
         String unit_price=jTable1.getValueAt(r, 6).toString();
        
         
        // SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
         //String date= sdm.format(Date_of_add);
         
         jTextField3.setText(mat_name);
         jComboBox1.setSelectedItem(mat_no);
         jTextField5.setText(mat_subcat_no);
         jTextField6.setText(rack_no);
         //jDateChooser1.setDateFormatString(date);
         jTextField8.setText(qty);
         jTextField9.setText(unit_price);
         jLabel5.setVisible(false);
         jTextField5.setVisible(false);
         try {
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date1=format.parse(date);
            jDateChooser1.setDate(date1);
        } catch (Exception e) {
            e.printStackTrace();
        }
         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
        
         tableload();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
       
            char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Quantity", JOptionPane.ERROR_MESSAGE);
        
      
    } 
        
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
       
                char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Unit price", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jTextField9KeyPressed

        private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
       
            
                char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Rack no", JOptionPane.ERROR_MESSAGE);
        
    }    
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       
        try {
            String filename=chooseFile();
            
        Document document=new Document(); 
        PdfWriter.getInstance(document,new FileOutputStream(filename+".pdf"));
          document.open();
          document.add(new Paragraph("----------------------------------------Add New Material----------------------------------------")); 
          document.add(new Paragraph(" ")); 
          document.add(new Paragraph("Material Name                 :"+jTextField3.getText()));
          document.add(new Paragraph("Material No                   :"+jComboBox1.getSelectedItem()));
          document.add(new Paragraph("Material Sub Cat No           :"+jTextField5.getText())); 
          document.add(new Paragraph("Rack  No                      :"+jTextField6.getText())); 
          document.add(new Paragraph("Date Of Added                 :"+jDateChooser1.getDate())); 
          document.add(new Paragraph("Quantity                      :"+jTextField8.getText())); 
          document.add(new Paragraph("Unit Price                    :"+jTextField9.getText()));
         
           document.close();
        JOptionPane.showMessageDialog(null,"Successfully Created.");
            
            
        } 
        catch (Exception e) {
        
          JOptionPane.showMessageDialog(null,"you have not create any file");
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

 private String chooseFile() {
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename =f.getAbsolutePath();
        return filename;
    }



}
