/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import test_new.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demo
 */
public class Daily_Machine_Details extends javax.swing.JInternalFrame {
    private int r;

    /**
     * Creates new form Daily_Machine_Details
     */
    public Daily_Machine_Details() {
        initComponents();
    }

     public void tableload(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from daily_machine_status");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("Machine_no"));
            v.add(rs.getString("Machine_name"));
            v.add(rs.getString("Receive_date"));
            v.add(rs.getString("No_of_machine_received"));
            v.add(rs.getString("description"));
            v.add(rs.getString("Store_keeper_job_id"));
           

            
            
             dtm.addRow(v);
      
           }
         }
         catch(Exception e){
         e.printStackTrace();
         
         }
        
        }
     
      void tableload(String Machi_no){
    
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from daily_machine_status where Machine_no Like'%"+Machi_no+"%'");
              while(rs.next()){  
                Vector v = new Vector();
                
           v.add(rs.getString("Machine_no"));
            v.add(rs.getString("Machine_name"));
            v.add(rs.getString("Receive_date"));
            v.add(rs.getString("No_of_machine_received"));
            v.add(rs.getString("description"));
            v.add(rs.getString("Store_keeper_job_id"));

            
            dtm.addRow(v);

              
              }
        
        }catch(Exception e){
            e.printStackTrace();
        }
      }

       public void tableload1(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from daily_mach_stat_2");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("machine_no"));
            v.add(rs.getString("name"));
            v.add(rs.getString("Deliver_date"));
            v.add(rs.getString("No_of_machine_deliver"));
            v.add(rs.getString("Descript"));
            v.add(rs.getString("Store_keeper_job_id"));
           

            
            
             dtm.addRow(v);
      
           }
         }
         catch(Exception e){
         e.printStackTrace();
         
         }
        
        }
     
        void tableload1(String Machi_no1){
    
    DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from daily_mach_stat_2 where machine_no Like'%"+Machi_no1+"%'");
              while(rs.next()){  
                Vector v = new Vector();
            v.add(rs.getString("machine_no"));
            v.add(rs.getString("name"));
            v.add(rs.getString("Deliver_date"));
            v.add(rs.getString("No_of_machine_deliver"));
            v.add(rs.getString("Descript"));
            v.add(rs.getString("Store_keeper_job_id"));

            
            dtm.addRow(v);

              
              }
        
        }catch(Exception e){
            e.printStackTrace();
        }
      }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        Search = new javax.swing.JToggleButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Daily Received and Delivered Machine Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 1330, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 90, 1330, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 20, 650));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Received Machine");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Delivered Machine");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel5.setText("Machine No :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel6.setText("Machine Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jLabel7.setText("No Of Machine :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jLabel8.setText("Description :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel9.setText("Store Keeper Job Id :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 20));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 200, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 200, -1));

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 200, -1));

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 200, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 200, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 200, -1));

        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField9MouseEntered(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Machine No ", "Machine Name", "Date", "No of Machines", "Description", "Store Keeper Job Id"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 720, 150));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Machine No", "Machine Name", "Date", "No of machine", "Description", "Store Keeper Job Id"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 720, 150));

        jToggleButton1.setText("Search");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 120, 30));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 120, 30));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 200, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 200, -1));

        jLabel11.setText("Received Machine No :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        jLabel12.setText("Delivered Machine No :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, -1));

        jToggleButton3.setText("Enter");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 120, 30));

        jToggleButton4.setText("Update");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 120, 30));

        jToggleButton5.setText("Clear");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("View Received Machine Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel13)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 730, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("View Delivered Machine Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel14)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 730, 30));

        jToggleButton2.setText("Print PDF Report");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 150, 120, 30));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        jDateChooser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooser1FocusLost(evt);
            }
        });
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 200, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 30, 650));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 200, -1));

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, 30));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 120, 30));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 120, 30));

        jButton4.setText("view");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 120, 30));

        jButton5.setText("view");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "910", "11", "12", "13", "14", "15", "16" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       
        try {
            
            String filename=chooseFile();
            
        Document document=new Document(); 
        PdfWriter.getInstance(document,new FileOutputStream(filename+".pdf"));
          document.open();
          document.add(new Paragraph("----------------------------------------Received Machines----------------------------------------")); 
          document.add(new Paragraph(" ")); 
          document.add(new Paragraph("Date                          :"+jDateChooser1.getDate()));
          document.add(new Paragraph("Material No                   :"+jComboBox1.getSelectedItem()));
          document.add(new Paragraph("Material Name                 :"+jTextField5.getText())); 
          document.add(new Paragraph("No Of Machines                :"+jTextField7.getText())); 
          document.add(new Paragraph("Store Keeper job Id           :"+jTextField9.getText())); 
          document.add(new Paragraph("Description                   :"+jTextArea1.getText())); 
          
          document.add(new Paragraph(" ")); 
          document.add(new Paragraph("----------------------------------------Delivered Machines----------------------------------------")); 
          document.add(new Paragraph(" ")); 
          document.add(new Paragraph("Date                          :"+jDateChooser2.getDate()));
          document.add(new Paragraph("Material No                   :"+jComboBox2.getSelectedItem()));
          document.add(new Paragraph("Material Name                 :"+jTextField6.getText())); 
          document.add(new Paragraph("No Of Machines                :"+jTextField8.getText())); 
          document.add(new Paragraph("Store Keeper job Id           :"+jTextField1.getText())); 
          document.add(new Paragraph("Description                   :"+jTextArea2.getText())); 
        
         
           document.close();
        JOptionPane.showMessageDialog(null,"Successfully Created.");
            
            
        }
        
        catch (Exception e) {
         JOptionPane.showMessageDialog(null,"you have not create any file");
        
        
        }
        
        
        
        
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

        if( (jTextField5.getText().isEmpty()) || (jTextField7.getText().isEmpty()) ||(jTextField9.getText().isEmpty()) ||(jTextArea1.getText().isEmpty()) ||(jDateChooser1.getDateFormatString().isEmpty())){
        
         JOptionPane.showMessageDialog(null, "enter the correct vales in textfield","Error in Text field",JOptionPane.ERROR_MESSAGE); 
         
        }
        else{
        String Machi_no=jComboBox1.getSelectedItem().toString();
        String Machi_name=jTextField5.getText();
        String Machi_nom=jTextField7.getText();
        String Machi_rec_des=jTextArea1.getText();
        String Store_kid=jTextField9.getText();
        Date  rdate=jDateChooser1.getDate();
        
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
        String date1= sdm.format(rdate);
        
        try {
            
             Statement st= db.getconnection().createStatement();
             st.executeUpdate("insert into daily_machine_status (Machine_no,Machine_name,Receive_date,No_of_machine_received,description,Store_keeper_job_id) values ('"+ Machi_no+"','"+Machi_name+"','"+ date1+"','"+Machi_nom+"','"+ Machi_rec_des+"','"+Store_kid+"')");
             JOptionPane.showMessageDialog(null,"Successfully Saved,',,");
             
               jComboBox1.setSelectedItem(null);
            jTextField5.setText(null);
            jTextField7.setText(null);
            jTextField9.setText(null);
            jTextArea1.setText(null);
            jDateChooser1.setDateFormatString(null);
             
             
        } catch (Exception e) {
            e.printStackTrace();
            
        }
     DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
        tableload();
        
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       
        String Machi_no=jTextField10.getText();
        
           if(Machi_no.equals("") ||Machi_no.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Machinet_no","Error in Machine_no",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
           tableload(Machi_no); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

        String Machi_no1=jTextField11.getText();
        
            if(Machi_no1.equals("") ||Machi_no1.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Machinet_no","Error in Machine_no",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
           tableload1(Machi_no1);
        
        
        
    }//GEN-LAST:event_SearchActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         if( (jTextField6.getText().isEmpty()) || (jTextField8.getText().isEmpty()) ||(jTextField1.getText().isEmpty()) ||(jTextArea2.getText().isEmpty()) ||(jDateChooser2.getDateFormatString().isEmpty())){
        
         JOptionPane.showMessageDialog(null, "enter the correct vales in textfield","Error in Text field",JOptionPane.ERROR_MESSAGE); 
         
        }
         else{
        String Machi_no1=jComboBox2.getSelectedItem().toString();
        String Machi_name1=jTextField6.getText();
        String Machi_nom1=jTextField8.getText();
        String Machi_del_des=jTextArea2.getText();
        String Store_kid1=jTextField1.getText();
        Date ddate=jDateChooser2.getDate();
        
         SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        String date2= sd.format(ddate);
        
        try {
            Statement st= db.getconnection().createStatement();
             st.executeUpdate("insert into daily_mach_stat_2 (machine_no,name,Deliver_date,No_of_machine_deliver, Descript,  Store_keeper_job_id) values ('"+ Machi_no1+"','"+Machi_name1+"','"+ date2+"','"+Machi_nom1+"','"+ Machi_del_des+"','"+Store_kid1+"')");
             JOptionPane.showMessageDialog(null,"Successfully Saved,',,");
             
              
               jComboBox2.setSelectedItem(null);
            jTextField6.setText(null);
            jTextField8.setText(null);
            jTextField1.setText(null);
            jTextArea2.setText(null);
            jDateChooser2.setDateFormatString(null);
             
             
            
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
       DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         dtm.setRowCount(0);
        tableload1();
        
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
      
        String Machi_no=jComboBox1.getSelectedItem().toString();
        String Machi_name=jTextField5.getText();
        String Machi_nom=jTextField7.getText();
        String Machi_rec_des=jTextArea1.getText();
        String Store_kid=jTextField9.getText();
        Date  rdate=jDateChooser1.getDate();
        
        SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
        String date1= sdm.format(rdate);
        
        try {
           Statement st= db.getconnection().createStatement();
           st.executeUpdate("update daily_machine_status set Machine_no='"+Machi_no+"',Machine_name='"+Machi_name+"',Receive_date='"+date1+"',No_of_machine_received='"+ Machi_nom+"',description='"+Machi_rec_des+"',Store_keeper_job_id='"+Store_kid+"' where Machine_no='"+Machi_no+"'");
           JOptionPane.showMessageDialog(null,"Successfully update,,,");
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
         tableload();
        
        
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         String Machi_no1=jComboBox2.getSelectedItem().toString();
        String Machi_name1=jTextField6.getText();
        String Machi_nom1=jTextField8.getText();
        String Machi_del_des=jTextArea2.getText();
        String Store_kid1=jTextField1.getText();
        Date ddate=jDateChooser2.getDate();
       //JOptionPane.showMessageDialog(, ddate+"");
         SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        String date2= sd.format(ddate);
        
      
        
        try {
           Statement st= db.getconnection().createStatement();
           st.executeUpdate("update  daily_mach_stat_2  set machine_no='"+Machi_no1+"',name='"+Machi_name1+"',Deliver_date='"+date2+"',No_of_machine_deliver='"+ Machi_nom1+"',Descript='"+Machi_del_des+"',Store_keeper_job_id='"+Store_kid1+"' where  machine_no='"+Machi_no1+"'");
           JOptionPane.showMessageDialog(null,"Successfully update,,,");
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         dtm.setRowCount(0);
        tableload1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
       
         String Machi_no=jComboBox1.getSelectedItem().toString();
         
          if(Machi_no.equals("")|| Machi_no.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the relevant row","Error selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getconnection().createStatement();
               st.executeUpdate("DELETE from daily_machine_status where Machine_no='"+Machi_no+"'");
               JOptionPane.showMessageDialog(null,"Successfully Deleted,,,");
           } catch (Exception e) {
               e.printStackTrace();
           }
       
       }
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
         tableload(); 
       
       
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         String Machi_no1=jComboBox2.getSelectedItem().toString();
          if(Machi_no1.equals("")|| Machi_no1.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the relevant row","Error selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getconnection().createStatement();
               st.executeUpdate("DELETE from daily_mach_stat_2 where Machine_no='"+Machi_no1+"'");
               JOptionPane.showMessageDialog(null,"Successfully Deleted,,,");
           } catch (Exception e) {
               e.printStackTrace();
           }
       
       }
         
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         dtm.setRowCount(0);
        tableload1();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        int r=jTable1.getSelectedRow();
        
         String  Machi_no=jTable1.getValueAt(r, 0).toString();
         String date1=jTable1.getValueAt(r, 2).toString();
         String Machi_nom=jTable1.getValueAt(r, 3).toString();
         String Machi_name=jTable1.getValueAt(r, 1).toString();
         String Machi_rec_des=jTable1.getValueAt(r, 4).toString();
         String  Store_kid=jTable1.getValueAt(r, 5).toString();
        
         
         jComboBox1.setSelectedItem(Machi_no);
         jTextField5.setText(Machi_name);
         jTextField7.setText(Machi_nom);
         jTextField9.setText(Store_kid);
         jTextArea1.setText(Machi_rec_des);
         jComboBox1.setVisible(false);
         jLabel5.setVisible(false);
         jComboBox2.setVisible(false);
        // jDateChooser1.setDateFormatString(date1);
           try {
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date11=format.parse(date1);
            jDateChooser1.setDate(date11);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       
        int r=jTable2.getSelectedRow();
        
         String  Machi_no1=jTable2.getValueAt(r, 0).toString();
         String date2=jTable2.getValueAt(r, 2).toString();
         String Machi_nom1=jTable2.getValueAt(r, 3).toString();
         String Machi_name1=jTable2.getValueAt(r, 1).toString();
         String Machi_del_des=jTable2.getValueAt(r, 4).toString();
         String  Store_kid1=jTable2.getValueAt(r, 5).toString();
        
           jComboBox2.setSelectedItem(Machi_no1);
         jTextField6.setText(Machi_name1);
         jTextField8.setText(Machi_nom1);
         jTextField1.setText(Store_kid1);
         jTextArea2.setText(Machi_del_des);
         jLabel5.setVisible(false);
         jComboBox2.setVisible(false);
         jComboBox1.setVisible(false);
         //jDateChooser2.setDateFormatString(date2);
         try {
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date111=format.parse(date2);
            jDateChooser2.setDate(date111);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
        
         tableload();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
         dtm.setRowCount(0);
        
         tableload1();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        
        
                      char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in No Of Machines", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        
                      char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in No Of Machines", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here

    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser1FocusLost
        // TODO add your handling code here:
   

        

    }//GEN-LAST:event_jDateChooser1FocusLost

    private void jTextField9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseEntered
      
          String Machi_nom1=jTextField8.getText();
          String Machi_nom=jTextField7.getText();
        
            int nom1=Integer.parseInt( Machi_nom1);
        int nom=Integer.parseInt(Machi_nom);
        if((nom<=nom1)){
            
        JOptionPane.showMessageDialog(null, "Please enter the Correct Amount","Error in No Of Machines", JOptionPane.ERROR_MESSAGE); 
        
        }
        else{
        
         System.out.println("lol1");
        
        }
        
    }//GEN-LAST:event_jTextField9MouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables

private String chooseFile() {
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename =f.getAbsolutePath();
        return filename;
    }

}
