/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import test_new.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demo
 */
public class Daily_mat_status extends javax.swing.JInternalFrame {

    /**
     * Creates new form Daily_mat_status
     */
    public Daily_mat_status() {
        initComponents();
    }

         public void tableload(){
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from daily_status");
           
           while(rs.next()){
                 Vector v = new Vector();
         
            v.add(rs.getString("Material_sub_cat_no"));
            v.add(rs.getString("Curr_date"));
            v.add(rs.getString("storekeeperJob_id"));
            v.add(rs.getString("unit_price"));
            v.add(rs.getString("Grn_note_no"));
            v.add(rs.getString("R_qty"));
             v.add(rs.getString("r_value"));
            v.add(rs.getString("G_req_note_no"));
            v.add(rs.getString("issued_qty"));
             v.add(rs.getString("i_value"));
            
           
            
             v.add(rs.getString("remain"));
             
             dtm.addRow(v);
      
           }
         }
         catch(Exception e){
         e.printStackTrace();
         
         }
        
        }
         
        void tableload(String mat_sub_cat){
    
       DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
           ResultSet rs= db.getconnection().createStatement().executeQuery("select * from  daily_status where Material_sub_cat_no Like'%"+mat_sub_cat+"%'");
              while(rs.next()){  
                Vector v = new Vector();
            
          
            v.add(rs.getString("Material_sub_cat_no"));
            v.add(rs.getString("Curr_date"));
            v.add(rs.getString("storekeeperJob_id"));
            v.add(rs.getString("unit_price"));
            v.add(rs.getString("Grn_note_no"));
            v.add(rs.getString("R_qty"));
             v.add(rs.getString("r_value"));
            v.add(rs.getString("G_req_note_no"));
            v.add(rs.getString("issued_qty"));
             v.add(rs.getString("i_value"));
            
           
            
             v.add(rs.getString("remain"));
             
            dtm.addRow(v);

              
              }
        
        }catch(Exception e){
            e.printStackTrace();
        }
      }

    public void date(){
        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
       
        jLabel11.setText(sd.format(d));
    }
         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Date:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setText("Material No:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel4.setText("Mat Sub Cat No:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        jLabel5.setText("unit Price :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel6.setText("Max Stock Level :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        jLabel7.setText("Min Stock Level :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        jLabel9.setText("Store Keeper Job Id :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 200, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 200, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 200, -1));

        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField6MouseEntered(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 200, -1));

        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField7MouseEntered(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 200, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Issued");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 260, 40));

        jLabel12.setText("Received Amount :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, 20));

        jLabel13.setText("GRN No  :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, -1, -1));

        jLabel14.setText("GRN No :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 260, -1, -1));

        jLabel15.setText("Issued Amount :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, -1, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 100, 140, -1));

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 140, 140, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 260, 140, -1));

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 300, 140, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("View Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(649, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1030, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 20, 330));

        jToggleButton1.setText("Search");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 120, 30));

        jLabel17.setText("Mat Sub Cat No :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, 20));
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mat sub cat No", "Date", "store keeper id", "Price", "GRN No", "Amount", "Value", "GRN No", "Amount", "Value", "Remain"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1310, 280));

        jToggleButton2.setText("Enter");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToggleButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jToggleButton2FocusGained(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 30));

        jToggleButton3.setText("Update");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, 30));

        jToggleButton4.setText("Clear");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 120, 30));

        jToggleButton6.setText("Print PDF Record");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 120, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1320, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 350, 10, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, 30));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 40, 30));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 40, 30));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, 20, 30));

        jLabel18.setText("Received");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        jLabel19.setText("Issued");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, -1, -1));

        jLabel20.setText("Others");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 360, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        jButton1.setText("view");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Received");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(98, 98, 98))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 250, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Daily Store Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1030, -1));

        jLabel21.setText("Receive Value :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, -1, -1));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 140, 20));

        jLabel23.setText("Issued Value :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 330, -1, -1));

        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 330, 140, 20));

        jLabel25.setText("Remain :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 200, 20));

        jLabel8.setText("Return Stock Level :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "910", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        if((jTextField3.getText().isEmpty()) ||(jTextField4.getText().isEmpty()) ||(jTextField5.getText().isEmpty())|| (jDateChooser1.getDateFormatString().isEmpty())||(jTextField6.getText().isEmpty())||(jTextField7.getText().isEmpty())||(jTextField8.getText().isEmpty())||(jTextField9.getText().isEmpty()) ||(jTextField10.getText().isEmpty())||(jTextField11.getText().isEmpty())||(jTextField12.getText().isEmpty())){
        
         JOptionPane.showMessageDialog(null, "enter the correct vales in textfield","Error in Text field",JOptionPane.ERROR_MESSAGE); 
            
        }
        else{
          String rsl=jTextField7.getText();
          String uprice=jTextField4.getText();
          String mat_no=jComboBox1.getSelectedItem().toString();
          String max_levl=jTextField5.getText();
          String store_kid=jTextField8.getText();
          String mat_sub_cat=jTextField3.getText();
          String min_level=jTextField6.getText();
          String R_grn=jTextField9.getText();
          String R_amount=jTextField10.getText();
          String I_grn=jTextField11.getText();
          String I_amount=jTextField12.getText();
          Date Date_of_add=jDateChooser1.getDate();
//        
          
          
          
               double nramount=Integer.parseInt(R_amount);
               double nuprice=Integer.parseInt(uprice);
             //  double nuprice1=Integer.parseInt(uprice);
               double ndamount=Integer.parseInt(I_amount);
               
               double rvalue= nramount* nuprice;
               
               double dvalue= ndamount* nuprice;
                
                double remain=nramount-ndamount;
                
               jLabel22.setText(Double.toString(rvalue));
               jLabel24.setText(Double.toString(dvalue));
                jLabel26.setText(Double.toString(remain));
                
          double rsl1=Integer.parseInt(rsl);
          
        if(remain<=rsl1){
      
     
       JOptionPane.showMessageDialog(null, "This material is low level");
    
    }
          
               
//        int mat_nos = Integer.parseInt(mat_no);
//        
          SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
          String date= sdm.format(Date_of_add);
          
          
         if(mat_sub_cat.equals("") ||mat_sub_cat.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Correct filed","Enter the fields",JOptionPane.ERROR_MESSAGE);
           return;
       }
          
          
//         
         try {
            Statement st= db.getconnection().createStatement();
            st.executeUpdate("insert into daily_status (Material_sub_cat_no, Curr_date, storekeeperJob_id, unit_price, Grn_note_no, R_qty, G_req_note_no, issued_qty, Return_req_level, max_stock_level, min_stock_level, meterial_no,i_value,r_value,remain) values ('"+mat_sub_cat+"','"+date+"','"+store_kid+"','"+uprice+"','"+ R_grn+"','"+R_amount+"','"+I_grn+"','"+I_amount+"','"+rsl+"','"+max_levl+"','"+min_level+"','"+mat_no+"','"+dvalue+"','"+rvalue+"','"+remain+"')");
        JOptionPane.showMessageDialog(null,"Successfully Saved,',,");
        
          
            jComboBox1.setSelectedItem(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
            jTextField10.setText(null);
            jTextField11.setText(null);
            jTextField12.setText(null);
            
            
            jDateChooser1.setDateFormatString(null);
        
        
        
        
         } catch (Exception e) {
             
              e.printStackTrace();
        }
        
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
           tableload();
         
          
        }
           
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       
        String mat_sub_cat=jTextField13.getText();
        
         if(mat_sub_cat.equals("") ||mat_sub_cat.equals(null)){
           JOptionPane.showMessageDialog(null,"Please Enter the Mat_sub_cat_no","Error in Sub_cat_no",JOptionPane.ERROR_MESSAGE);
           return;
       }
           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
           tableload(mat_sub_cat); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

         String rsl=jTextField7.getText();
          String uprice=jTextField4.getText();
          String mat_no=jComboBox1.getSelectedItem().toString();
          String max_levl=jTextField5.getText();
          String store_kid=jTextField8.getText();
          String mat_sub_cat=jTextField3.getText();
          String min_level=jTextField6.getText();
          String R_grn=jTextField9.getText();
          String R_amount=jTextField10.getText();
          String I_grn=jTextField11.getText();
          String I_amount=jTextField12.getText();
          Date Date_of_add=jDateChooser1.getDate();
          
          SimpleDateFormat sdm = new SimpleDateFormat("yyyy-MM-dd");
          String date= sdm.format(Date_of_add);
          
             double nramount=Integer.parseInt(R_amount);
               double nuprice=Integer.parseInt(uprice);
               double ndamount=Integer.parseInt(R_amount);
               double idamount=Integer.parseInt(I_amount);
               double rvalue= nramount* nuprice;
               
                double dvalue= nuprice* idamount;
                
                double remain=nramount-ndamount;
                
                jLabel22.setText(Double.toString(rvalue));
                jLabel24.setText(Double.toString(dvalue));
                jLabel26.setText(Double.toString(remain));
          
          
          
          
          
          try {
            
               Statement st= db.getconnection().createStatement();
               st.executeUpdate("update daily_status set Material_sub_cat_no='"+mat_sub_cat+"',Curr_date='"+date+"',storekeeperJob_id='"+ store_kid+"',unit_price='"+uprice+"',Grn_note_no='"+ R_grn+"', R_qty='"+ R_amount+"',G_req_note_no='"+I_grn+"', issued_qty='"+I_amount+"',Return_req_level='"+rsl+"',max_stock_level='"+max_levl+"', min_stock_level='"+min_level+"',meterial_no='"+mat_no+"',i_value='"+dvalue+"',r_value='"+rvalue+"',remain='"+remain+"' where Material_sub_cat_no='"+mat_sub_cat+"'");
               JOptionPane.showMessageDialog(null,"Successfully update,,,");
             
        } catch (Exception e) {
            
            e.printStackTrace();
        }
          
          DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
          dtm.setRowCount(0);
          tableload();
         
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed

          String mat_sub_cat=jTextField3.getText();
        
          
           if(mat_sub_cat.equals("")|| mat_sub_cat.equals(null)){
            JOptionPane.showMessageDialog(null, "Please select the relevant row","Error selection", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to delete this");
       
       if(x==0){
       
           try {
               com.mysql.jdbc.Statement st= (com.mysql.jdbc.Statement) db.getconnection().createStatement();
               st.executeUpdate("DELETE from  daily_status where Material_sub_cat_no='"+mat_sub_cat+"'");
               JOptionPane.showMessageDialog(null,"Successfully Deleted,,,");
           } catch (Exception e) {
               e.printStackTrace();
           }
       
       }
       
       DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
       dtm.setRowCount(0);
       tableload();
       
        
        
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
         int r=jTable1.getSelectedRow();
        
          String  mat_sub_cat=jTable1.getValueAt(r, 0).toString();
         String store_kid=jTable1.getValueAt(r, 2).toString();
         String  date=jTable1.getValueAt(r, 1).toString();
         String uprice=jTable1.getValueAt(r, 3).toString();
         String R_grn=jTable1.getValueAt(r, 4).toString();
         String R_amount=jTable1.getValueAt(r, 5).toString();
         String rvalue=jTable1.getValueAt(r, 6).toString();
         String I_grn=jTable1.getValueAt(r, 7).toString();
         String I_amount=jTable1.getValueAt(r, 8).toString();
         String dvalue=jTable1.getValueAt(r, 9).toString();
         String remain=jTable1.getValueAt(r, 10).toString();

         
        jTextField3.setText(mat_sub_cat);
        jTextField8.setText(store_kid);
       // jDateChooser1.setDateFormatString(date);
        jTextField4.setText(uprice);
        jTextField9.setText(R_grn);
        jTextField10.setText(R_amount);
        jTextField11.setText(I_grn);
        jTextField12.setText(I_amount);
        jLabel22.setText(rvalue);
        jLabel24.setText(dvalue);
        jLabel26.setText(remain);
        jLabel6.setVisible(false);
        jTextField5.setVisible(false);
        jLabel7.setVisible(false);
        jTextField6.setVisible(false);
        jLabel8.setVisible(false);
        jTextField7.setVisible(false);
        jLabel3.setVisible(false);
        jComboBox1.setVisible(false);
        jLabel4.setVisible(false);
        jTextField3.setVisible(false);
           try {
            DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date1=format.parse(date);
            jDateChooser1.setDate(date1);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
        
         tableload();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
                     char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Unit price", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
      
                      char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Max Stock Level", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
                    char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Min Stock Level", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
                     char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Return Stock Level", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
                     char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Received Amount", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
                     char c = evt.getKeyChar();
    if (Character.isDigit(c)) {
        
    } else {
        JOptionPane.showMessageDialog(null,"Enter only numeric digits","Error in Issued Amount", JOptionPane.ERROR_MESSAGE);
        
    } 
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
       
        String R_amount=jTextField10.getText();
        String  I_amount=jTextField12.getText();
        int ramt=Integer.parseInt(R_amount);
        int iamt=Integer.parseInt(I_amount);
        if((ramt < iamt)){
        
         JOptionPane.showMessageDialog(null, "Please enter the Correct Amount","Error in Amount", JOptionPane.ERROR_MESSAGE); 
        
        }
        else{
        
         System.out.println("lol1");
        }
       
        
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jTextField6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseEntered
       
       
        
        
    }//GEN-LAST:event_jTextField6MouseEntered

    private void jTextField7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseEntered
        
        
        String max_levl=jTextField5.getText();
        String min_level=jTextField6.getText();
        
            int mlevel=Integer.parseInt(max_levl);
        int minlevel=Integer.parseInt(min_level);
        if((mlevel < minlevel)){
        
         JOptionPane.showMessageDialog(null, "Please enter the Correct Level","Error in level", JOptionPane.ERROR_MESSAGE); 
        
        }
        else{
        
         System.out.println("lol1");
        }
        
    }//GEN-LAST:event_jTextField7MouseEntered

    private void jToggleButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseEntered
       
       
        
    }//GEN-LAST:event_jToggleButton2MouseEntered

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        
      
        
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jToggleButton2FocusGained
       
       
    }//GEN-LAST:event_jToggleButton2FocusGained

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        
        
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        try {
         String filename=chooseFile();
            
        Document document=new Document(); 
        PdfWriter.getInstance(document,new FileOutputStream(filename+".pdf"));
          document.open();
          document.add(new Paragraph("----------------------------------------Daily Store Details----------------------------------------")); 
          document.add(new Paragraph(" ")); 
          document.add(new Paragraph("Date                          :"+jDateChooser1.getDate()));
          //document.add(new Paragraph("Material No                   :"+jTextField2.getText()));
          document.add(new Paragraph("Material Sub Cat No           :"+jTextField3.getText())); 
          document.add(new Paragraph("Unit Price                    :"+jTextField4.getText())); 
          document.add(new Paragraph("Store Keeper job Id           :"+jTextField8.getText())); 
          document.add(new Paragraph("Remain                        :"+jLabel26.getText())); 
          //document.add(new Paragraph("Max Stock Level               :"+jTextField5.getText()));
          //document.add(new Paragraph("Min Stock Level               :"+jTextField6.getText()));
          //document.add(new Paragraph("Return Stock Level            :"+jTextField7.getText()));
          document.add(new Paragraph("Good Receive Note No          :"+jTextField9.getText()));
          document.add(new Paragraph("Received Amount               :"+jTextField10.getText()));
          document.add(new Paragraph("Receive  Value                :"+jLabel22.getText()));
          document.add(new Paragraph("Good Issued Note No           :"+jTextField11.getText()));
          document.add(new Paragraph("Issued Amount                 :"+jTextField12.getText()));
          document.add(new Paragraph("Issued Value                  :"+jLabel24.getText()));
         
          
           document.close();
        JOptionPane.showMessageDialog(null,"Successfully Created.");    
        } 
        catch (Exception e) {
        JOptionPane.showMessageDialog(null,"you have not create any file");
        }
       
        
        
        
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables

 private String chooseFile() {
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename =f.getAbsolutePath();
        return filename;
    }


}
